### ISSUE TITLE
Installation failed on LineageOS 14.1

### ISSUE THREAD

**Issue by godfuture** [VR-25/acc#103]
I have been using acc for a long time, but it seems since a year I cannot install acc anymore. When installing, it always tells "installation failed!". 

Is acc not compatibel with Android 7 anymore? If yes, which version should Android 7 users install?

**Comment by VR-25** [comment]
ACC should install on Android 4.0+ (or even lower, if mksh is manually upgraded).

I would like to see logs.
Try installing the latest version and share init.log and install.log from `/sdcard/Documents/vr25/acc/logs/`.

**Comment by godfuture** [comment]
I cannot open /sdcard/Documents/vr25 no matter what app I use. Owner is root and group is everybody. Both have read permission.
What could I do?

**Comment by VR-25** [comment]
Try `/data/media/0/Documents/vr25/`.

**Comment by godfuture** [comment]
/data/media/0/Documents/vr25/ worked for me, thanks.
[Acc.zip](https://github.com/VR-25/acc/files/6881613/Acc.zip)

**Comment by VR-25** [comment]
Have you tried the [latest](https://github.com/vr25/acc/releases/latest) release?

**Comment by godfuture** [comment]
Latest release work just fine for me. Now also the AccA app works. Thanks!
