### ISSUE TITLE
doesn't stop charging and some bugs

### ISSUE THREAD

**Issue by kevin01523** [VR-25/acc#114]
[continueschargeacc-logs-tulip.tar.gz.zip](https://github.com/VR-25/acc/files/7085689/continueschargeacc-logs-tulip.tar.gz.zip)
i set a limit where it should stop charging on 70% but still continue to charge. although it doesn't appear to be charging at a glance but on closer look when i plug the charger it changes the current but doesn't notify

![Screenshot_20210901-010741](https://user-images.githubusercontent.com/8380242/131547470-f1027083-574f-49d8-9388-ae06fdb0636e.jpg)
![Screenshot_20210901-010748](https://user-images.githubusercontent.com/8380242/131547485-8b228f09-6d0b-40f1-b281-40b223d1f5c3.jpg)
![Screenshot_20210901-011029](https://user-images.githubusercontent.com/8380242/131547498-cdbeca2d-a824-4724-a570-1309f07784ce.jpg)
![Screenshot_20210901-011039](https://user-images.githubusercontent.com/8380242/131547514-90046576-239e-49a3-b984-b0199824ae29.jpg)

if unplugged

![Screenshot_20210901-011935](https://user-images.githubusercontent.com/8380242/131547676-f4d8585d-03b5-4c72-882a-87c8ff84bdab.jpg)
![Screenshot_20210901-011953](https://user-images.githubusercontent.com/8380242/131547687-484c74da-15e7-47f2-ad82-0c9026365ba6.jpg)

the log after i restarted same issue
[acc-logs-tulip.tar.gz.zip](https://github.com/VR-25/acc/files/7085741/acc-logs-tulip.tar.gz.zip)

this the log after downgrading into Advanced Charging Controller v2021.8.4 (202108040)  which fixed the issue

[acc-logs-tulipAccv2021.8.4.tar.bz2.zip](https://github.com/VR-25/acc/files/7085865/acc-logs-tulipAccv2021.8.4.tar.bz2.zip)

**Comment by VR-25** [comment]
Share the output of `acc -t` (latest acc).

**Comment by kevin01523** [comment]
`.../files/home # acc -t

(!) Charger must be plugged to continue...
(i) Alright, this may take a minute or so...

(i) [battery/charging_enabled 1 0] works
- battIdleMode=false

(i) [battery/input_suspend 0 1] works
- battIdleMode=false

(!) [dc/input_suspend 0 1] won't work`

**Comment by VR-25** [comment]
Run `acc -s s="battery/input_suspend 0 1 --"` and see whether charging actually stops.

**Comment by kevin01523** [comment]
it only stops by a second then continue to to charge only removed or updates the battery and charger light indicator

before
![Screenshot_20210901-201331](https://user-images.githubusercontent.com/8380242/131669527-c3d8b9eb-80b6-45ee-8805-ea00cb5c7669.jpg)


after

![Screenshot_20210901-201519](https://user-images.githubusercontent.com/8380242/131669592-f1463a8a-cbc5-4167-bcfc-a91cfedf257e.jpg)

**Comment by VR-25** [comment]
Run `acc -s s=` to revert to _automatic_ charging switch.
Since the charging status actually changes, this seems to be a kernel issue.
ACC actually _thinks_ charging stopped - because _battery/status_ says so.
The kernel is _lying_.

Try current and voltage based charging control.
Current: `acc -s s=0`
Voltage: `acc -s s=3700`
Test one at a time.

**Comment by VR-25** [comment]
Are you sure the previous acc version actually works?

**Comment by kevin01523** [comment]
yes its on automatic on my end as always
then it defaults into battery charging enabled switch with cycling allowed

i think i suspect the issue is on the new version
once the cycling through switches is enabled after testing the switches somehow
battery/input_suspend  gets used /prioritized even if
the default one is battery/charging_enabled 1 0 ill test more i guess
on previous version it may skip a percent or two(rarely) but eventually the charging stops but now it can charge into 100 unknowingly

**Comment by kevin01523** [comment]
> Are you sure the previous acc version actually works?

Yep tried and tested same setup update 21 8 4 properly stops charging at auto
Or won't charge after replugged the charger


8 31
Somehow won't stop charging(after a few more test both switches seems affected charging enabled and suspend) after passes the limit and will charge up to 100 with the charging status as false but you can see it charging based on current and what kind of charge if its taper or fast charging

**Comment by programminghoch10** [comment]
Hey, I have the same issue on willow, old versions worked flawlessly, new one does not stop charging. I first thought it might be a problem with ACCA, so I'll test to downgrade ACCA only first.

**Comment by VR-25** [comment]
Try [this](https://github.com/VR-25/acc/files/7105629/acc_v2021.9.1_.202109010.zip) new build.

**Comment by programminghoch10** [comment]
Short test seems to work, I'll try in my usual cycle this night.

**Comment by VR-25** [comment]
[Here's](https://github.com/VR-25/acc/files/7108384/acc_v2021.9.3.1_.202109031.zip) a newer build.

**Comment by programminghoch10** [comment]
@VR-25 the ACC Daemon crashed on me again. I'll send the log on Sunday.

**Comment by kevin01523** [comment]
Did a quick test it does stop after hitting the stop charging at value but once I tried to toggle off the automatic cycling through switches and save the phone seems to start charging without changingvits status from discharging.

I used the last build provided

**Comment by programminghoch10** [comment]
[acc-logs-willow.tar.gz](https://github.com/VR-25/acc/files/7112142/acc-logs-willow.tar.gz)
Acc again crashed just while charging in the low 30%, it didn't even nearly hit the stop limit.

**Comment by VR-25** [comment]
A [new](https://github.com/VR-25/acc/releases/tag/v2021.9.5) release is up.

**Comment by kevin01523** [comment]
here are some new logs i have encountered a few weird bugs
like config getting reset to previous setting or config changes doesn't save. on acca had to re edit and save a few times.it doesn't always happen but it happens.

it tries to charge for a second then stops(might be the result of different config im seeing and the actual config being used via acca)


i guess you already know that cooldown is broken as it stops and resume in less than 5-10 seconds intervals contrary to the config

**Comment by programminghoch10** [comment]
For me everything works now. It ran several cycles without any problems.

**Comment by kevin01523** [comment]
I think the only really broken one is the cooldown time
The config daving i think its a acca bug where there's two simultaneous commands setting into the config and it hangs

**Comment by VR-25** [comment]
I still could not reproduce the cooldown issue.
Cooldown is working well for me.

Here's a new prerelease:
https://github.com/VR-25/acc/files/7138273/acc_v2021.9.9.1_.202109091.zip

**Comment by kevin01523** [comment]
Here a log from just before the prerelease gonna upload the  prerelease log after

From what i observed cooldown goes haywire if i use a fast charger with qc 3.0 with a current limited by acc on my other charger it goes fine kinda

**Comment by kevin01523** [comment]
It crashes once i plug in a charger any charger will do tested 3 of em

**Comment by VR-25** [comment]
It seems AccA is causing problems.
I've not been using it lately.
See if acc alone has any major issue.

**Comment by VR-25** [comment]
[acc_v2021.9.10_(202109100).zip](https://github.com/VR-25/acc/files/7143322/acc_v2021.9.10_.202109100.zip)

**Comment by kevin01523** [comment]
Crashes when a charger is plugged i did set things via command so no acca
[acc-logs-tulip.tar.gz](https://github.com/VR-25/acc/files/7143606/acc-logs-tulip.tar.gz)

**Comment by VR-25** [comment]
[acc_v2021.9.10.1_(202109101).zip](https://github.com/VR-25/acc/files/7143873/acc_v2021.9.10.1_.202109101.zip)

**Comment by kevin01523** [comment]
Crashes when a charger is plugged i did set things via command so no acca
[Uploading acc-logs-tulip.tar.gz…]()

**Comment by kevin01523** [comment]
[acc-logs-tulip.tar.gz](https://github.com/VR-25/acc/files/7144180/acc-logs-tulip.tar.gz)
Cooldown seems to work now i haven't tried or set any new value after updating acc i guess ill observe and charge it for a few cycle the. Upload logs

**Comment by kevin01523** [comment]
It didn't report that its charging but it is suddenly
After changing the max current not sure what really happened
Restarting acc from term fixed it and the switches git set to auto
[acc-logs-tulip.tar.gz](https://github.com/VR-25/acc/files/7147152/acc-logs-tulip.tar.gz)
Logs for details

**Comment by VR-25** [comment]
I noticed that you're using `cooldownCurrent=700`.
Perhaps your device does not support this. Hence, cooldown is failing.

Do your max charging current and voltage limits work?

Try running acc and cooldown without any current and voltage limits.

You may want to read about `current_workaround` (README.html).

Upgrade acc.
acc_v2021.9.11_(202109110).zip](https://github.com/VR-25/acc/files/7147378/acc_v2021.9.11_.202109110.zip)

**Comment by kevin01523** [comment]
Cooldown works since 9.10.1 i just encountered a few bugs i think
As in charging is not reported or device says discharging but not really and in that situation current is fixed on the one i set and cooldown works too. I just haven't tried letting it reach the 
Stop charging capacity.just got the log while its happening and uploaded it.

cooldownCurrent=700
Do work and current do go from 1200 or 1600 into 650-699 during the 13-15 cooldown

Ill upload the log for 9.11 later I'm letting it charge for a few cycles for now

**Comment by kevin01523** [comment]
I just noticed it breaks the Acc -f 
Or the charge to capacity without restrictions
[acc-logs-tulip.tar.gz](https://github.com/VR-25/acc/files/7148408/acc-logs-tulip.tar.gz)

**Comment by VR-25** [comment]
What exactly is going on with `acc -f`?

**Comment by kevin01523** [comment]
`
  -f|--force|--full [capacity]   Charge once to a given capacity (default: 100%), without restrictions
    e.g.,
      acc -f 95 (charge to 95%)
      acc -f (charge to 100%)
    Note: if the desired % is less than pause_capacity, use acc -e #%
`

**Comment by VR-25** [comment]
[acc_v2021.9.12_(202109120).zip](https://github.com/VR-25/acc/files/7149752/acc_v2021.9.12_.202109120.zip)

**Comment by kevin01523** [comment]
Only stops charging or will charge for a second then stop charging
[acc-logs-tulip.tar.gz](https://github.com/VR-25/acc/files/7149778/acc-logs-tulip.tar.gz)

**Comment by VR-25** [comment]
Still, I'm unable to reproduce the issues you're facing.
Try resetting the config, rebooting, then testing `acc -d`, `acc -d` and `acc -t`.

**Comment by Donzi84** [comment]
good evening,

I 've dowloaded acc_v2021.9.12_(202109120).zip, How can I install it with magisk? my magisk doen't recogniz zip file.

Thanks 
stefano

**Comment by kevin01523** [comment]
Here's the log for the test i have not done anything else
[acc-logs-tulip.tar.gz](https://github.com/VR-25/acc/files/7153643/acc-logs-tulip.tar.gz)

**Comment by kevin01523** [comment]
> good evening,
> 
> I 've dowloaded acc_v2021.9.12_(202109120).zip, How can I install it with magisk? my magisk doen't recogniz zip file.
> 
> Thanks
> stefano

Try flashing it via acc

**Comment by VR-25** [comment]
> Here's the log for the test i have not done anything else
> [acc-logs-tulip.tar.gz](https://github.com/VR-25/acc/files/7153643/acc-logs-tulip.tar.gz)
> It did start charging now after i did start acc via wizard but
> Acc -d only stopped acc also charging or atleast charging status
> 
> Here's the log after changing the config and starting acc then replugged the charger
> [acc-logs-tulip.tar.gz](https://github.com/VR-25/acc/files/7153686/acc-logs-tulip.tar.gz)

Ok, now I found something relevant!
Working on a new build...

**Comment by VR-25** [comment]
> good evening,
> 
> I 've dowloaded acc_v2021.9.12_(202109120).zip, How can I install it with magisk? my magisk doen't recogniz zip file.
> 
> Thanks
> stefano

Magisk is supposed to recognize zip files.
Are you sure that's the issue?
Anyway try using `acc -F` (wizard) or `acc -F /path/to/zip` to flash the zip.
It this also fails, you probably have a corrupt archive. Redownload the zip and try again.

**Comment by VR-25** [comment]
[acc_v2021.9.13_(202109130).zip](https://github.com/VR-25/acc/files/7154160/acc_v2021.9.13_.202109130.zip)

**Comment by Donzi84** [comment]
> [acc_v2021.9.13_(202109130).zip](https://github.com/VR-25/acc/files/7154160/acc_v2021.9.13_.202109130.zip)

I've installed 9.13 but how can select it in acca?
![Screenshot_20210913-174807_AccA](https://user-images.githubusercontent.com/58210860/133116841-b8878cbd-3eb8-4b7f-aa6a-cf49f010f5b2.png)

**Comment by VR-25** [comment]
You don't have to.
This almost always irrelevant.

**Comment by Donzi84** [comment]
> You don't have to.
> This is almost always irrelevant.

ok, I'm testing a charching on a Samsung Tab4 sm-t335 with the acc    acc_v2021.9.13_(202109130).zip
This evening I tell you if it works.

**Comment by kevin01523** [comment]
New logs for 13 i guess current control still affect the acc force charge command

Im using acca to monitor the current change without changing the config with it
[acc-logs-tulip.tar.gz](https://github.com/VR-25/acc/files/7156408/acc-logs-tulip.tar.gz)

**Comment by Donzi84** [comment]
> [acc_v2021.9.13_(202109130).zip](https://github.com/VR-25/acc/files/7154160/acc_v2021.9.13_.202109130.zip)

It works!!!!!!! charge really stopped at 80 percent. Even after a long time the percentage no longer rises. @kevin01523 is the same for you?
@VR-25 thanks a lot

**Comment by Donzi84** [comment]
> [acc_v2021.9.13_(202109130).zip](https://github.com/VR-25/acc/files/7154160/acc_v2021.9.13_.202109130.zip)

It doesn't work.  It stopped at 80% for a while but then it resumes charging. 

Stefano

**Comment by VR-25** [comment]
> > [acc_v2021.9.13_(202109130).zip](https://github.com/VR-25/acc/files/7154160/acc_v2021.9.13_.202109130.zip)
> 
> It doesn't work. It stopped at 80% for a while but then it resumes charging.
> 
> Stefano

Unless you grab logs (`acc -le`) right after the occurrence of an issue, It takes longer for me to figure out what went wrong.

**Comment by Donzi84** [comment]
> > > [acc_v2021.9.13_(202109130).zip](https://github.com/VR-25/acc/files/7154160/acc_v2021.9.13_.202109130.zip)
> > 
> > 
> > It doesn't work. It stopped at 80% for a while but then it resumes charging.
> > Stefano
> 
> Unless you grab logs (`acc -le`) right after the occurrence of an issue, It takes longer for me to figure out what went wrong.

Could you please explain me how todo a log?
Thanks a lot
Stefano

**Comment by VR-25** [comment]
> New logs for 13 i guess current control still affect the acc force charge command
> 
> Im using acca to monitor the current change without changing the config with it
> [acc-logs-tulip.tar.gz](https://github.com/VR-25/acc/files/7156408/acc-logs-tulip.tar.gz)
> Cooldown seems to work fine

Due to an error from the previous build, you have two charging switches set.
This may be causing issues.
Run `acc -s s=` to reset that part of the config.

**Comment by VR-25** [comment]
> > > > [acc_v2021.9.13_(202109130).zip](https://github.com/VR-25/acc/files/7154160/acc_v2021.9.13_.202109130.zip)
> > > 
> > > 
> > > It doesn't work. It stopped at 80% for a while but then it resumes charging.
> > > Stefano
> > 
> > 
> > Unless you grab logs (`acc -le`) right after the occurrence of an issue, It takes longer for me to figure out what went wrong.
> 
> Could you please explain me how todo a log?
> Thanks a lot
> Stefano

Whenever to come across an issue, run `acc -le`.
It'll pack all logs into a compressed archive that you can share.
No personal information is ever included.
The commands prints the location of the generated log archive.

**Comment by Donzi84** [comment]
> > Could you please explain me how todo a log?
> > Thanks a lot
> > Stefano
> 
> Whenever you come across an issue, run `acc -le`.
> It'll pack all logs into a compressed archive that you can share.
> No personal information is ever included.
> The command prints the location of the generated log archive.

where have I to write the code acc -le? in the shell? in magisk? or in acca?
thanks you in advance.
Stefano

**Comment by VR-25** [comment]
Shell, as root
Two choices
1. `su` then `acc -le`
2. Just `su -c acc -le`

**Comment by Donzi84** [comment]
![Screenshot_20210913-221312_Terminal](https://user-images.githubusercontent.com/58210860/133150553-857c444f-0c44-4e80-ab7c-4619fdb042f4.png)
I don't understand where save the file .gz how can I access? Thanks

**Comment by VR-25** [comment]
You would have to use a root file manager.
But here's another way:
On this same terminal, _paste_ and run `cp /data/adb/vr25/acc-data/logs/acc-*.gz /sdcard/Download/`.
After this, you'll find the file in your Download directory.

**Comment by Donzi84** [comment]
> You would have to use a root file manager.
> But here's another way:
> On this same terminal, _paste_ and run `cp /data/adb/vr25/acc-data/logs/acc-*.gz /sdcard/Download/`.
> After this, you'll find the file in your Download directory.

Hereby the file. Thanks a lot for your patience. :)
Stefano

[acc-logs-milletlte.tar.gz](https://github.com/VR-25/acc/files/7157282/acc-logs-milletlte.tar.gz)

**Comment by VR-25** [comment]
While I analyze the logs further, see if charging control works as expected after running `acc -s s=` on terminal.

**Comment by Donzi84** [comment]
> analyze the logs further, see if charging control works as expected after running `acc -s s=` on terminal.

I've tried acc -s s= nut nothing is changed. It doesn't stop at 80percent.

Thnaks 
Stefano

**Comment by VR-25** [comment]
> I've tried acc -s s= nut nothing is changed. It doesn't stop at 80percent.
> 
> Thnaks
> Stefano

What's the output of `acc -t; acc -sp sw`?

**Comment by kevin01523** [comment]
`acc -t; acc -sp sw

(!) Charger must be plugged to continue...
(i) Alright, this may take a minute or so...

(i) [battery/charging_enabled 1 0] works
- battIdleMode=false

(i) [battery/input_suspend 0 1] works
- battIdleMode=false

(!) [battery/step_charging_enabled 1 0] won't work

(!) [dc/input_suspend 0 1] won't work


charging_switch=battery/charging_enabled 1 0`


Heres a new log
[acc-logs-twolip.tar.gz](https://github.com/VR-25/acc/files/7162447/acc-logs-twolip.tar.gz)

**Comment by Donzi84** [comment]
acc -t; acc -sp sw

![241800716_663413761303233_5177279312833375417_n](https://user-images.githubusercontent.com/58210860/133288468-b0ab1747-6851-4d0f-ad0e-4d902fb555d7.jpg)

**Comment by VR-25** [comment]
[acc_v2021.9.15.1_(202109151).zip](https://github.com/VR-25/acc/files/7172169/acc_v2021.9.15.1_.202109151.zip)

**Comment by Donzi84** [comment]
[acc-logs-milletlte-15-08-2021.tar.gz](https://github.com/VR-25/acc/files/7173247/acc-logs-milletlte-15-08-2021.tar.gz)
I've tested 2021.9.15.1.zip Stopped for a while and restart charge.

Attacched log

Thanks for your efforts.
Stefano

**Comment by kevin01523** [comment]
Feels buggy to me can't determine if the charger is plugged had manually unplug and replug
Battery in icon shows charging but on acca says otherwise but it shows fast charging status.
[acc-logs-tulip.tar.gz](https://github.com/VR-25/acc/files/7173324/acc-logs-tulip.tar.gz)

**Comment by Donzi84** [comment]
> Feels buggy to me can't determine if the charger is plugged had manually unplug and replug
> Battery in icon shows charging but on acca says otherwise but it shows fast charging status.
> Shows positive current when not charging and negative if charging
> 
> [acc-logs-tulip.tar.gz](https://github.com/VR-25/acc/files/7173324/acc-logs-tulip.tar.gz)

the same here

**Comment by VR-25** [comment]
https://github.com/VR-25/acc/files/7176032/acc_v2021.9.16.1_.202109161.zip

**Comment by kevin01523** [comment]
Charging works fine
Only thing broke i noticed is cooldown is broken
It only charge for 8 seconds
Seems to stop charging after passing the capacity control charging

1st log
[acc-logs-tulip.tar.gz](https://github.com/VR-25/acc/files/7176591/acc-logs-tulip.tar.gz)
2nd log
[acc-logs-tulip.tar.gz](https://github.com/VR-25/acc/files/7176597/acc-logs-tulip.tar.gz)

**Comment by VR-25** [comment]
[acc_v2021.9.16.2_(202109162).zip](https://github.com/VR-25/acc/files/7176595/acc_v2021.9.16.2_.202109162.zip)

**Comment by kevin01523** [comment]
[acc-logs-tulip.tar.gz](https://github.com/VR-25/acc/files/7176645/acc-logs-tulip.tar.gz)
Seems that the daemon crashed while i was editing config didn't notice it until i saved the config

**Comment by VR-25** [comment]
Refer to issue #106 for newer builds.

**Comment by Donzi84** [comment]
> [acc_v2021.9.16.2_(202109162).zip](https://github.com/VR-25/acc/files/7176595/acc_v2021.9.16.2_.202109162.zip)

doen't work :(

**Comment by VR-25** [comment]
[acc_v2021.9.17_(202109170).zip](https://github.com/VR-25/acc/files/7188476/acc_v2021.9.17_.202109170.zip)

**Comment by kevin01523** [comment]
[acc-logs-tulip.tar.gz](https://github.com/VR-25/acc/files/7188530/acc-logs-tulip.tar.gz)
Log after install and normal usage.

Log after acc -t command
[acc-logs-tulip.tar.gz](https://github.com/VR-25/acc/files/7188536/acc-logs-tulip.tar.gz)

**Comment by Donzi84** [comment]
> [acc_v2021.9.17_(202109170).zip](https://github.com/VR-25/acc/files/7188476/acc_v2021.9.17_.202109170.zip)

It doen't work on tab 4 8 sm-t335 :)

**Comment by kevin01523** [comment]
> > [acc_v2021.9.17_(202109170).zip](https://github.com/VR-25/acc/files/7188476/acc_v2021.9.17_.202109170.zip)
> 
> It doen't work on tab 4 8 sm-t335 :(

Provide logs so he can look into it

**Comment by Donzi84** [comment]
> [acc_v2021.9.17_(202109170).zip](https://github.com/VR-25/acc/files/7188476/acc_v2021.9.17_.202109170.zip)
[acc-logs-milletlte-19-09-2021.tar.gz](https://github.com/VR-25/acc/files/7192500/acc-logs-milletlte-19-09-2021.tar.gz)

hereby a log for 17.9 version that doesn't work

Thanks
Stefano

**Comment by VR-25** [comment]
The remaining issues are all kernel-related.
Kernel patches are required.

I try to come up with workarounds.
Often it takes a while.
Sometimes it takes forever to find a solution.
Nevertheless, I keep looking.

**Comment by Donzi84** [comment]
> The remaining issues are all kernel-related.
> Kernel patches are required.
> 
> I try to come up with workarounds.
> Often it takes a while.
> Sometimes it takes forever to find a solution.
> Nevertheless, I keep looking.

the strange thing is that with original rom it works fine. the problems are come with lineage rom.

Thanks
Stefano

**Comment by VR-25** [comment]
The ROM itself is irrelevant.
If you manage to find another kernel, give it a try.

**Comment by Donzi84** [comment]
> The ROM itself is irrelevant.
> If you manage to find another kernel which works with that ROM, give it a try.

https://sfirmware.com/downloads-file/20293/SM-T335_1_20150819180000_jubgub5sn7

with this rom all worked fine.  kernel isn't in the rom?. sorry for my ignorance :)

Stefano

**Comment by VR-25** [comment]
All regular (i.e., non-GSI) ROMs, including full firmware packs, ship with a kernel.
The kernel is the core of the operating system.
Without it, there's no access to the hardware.
Look for a custom kernel for your device on XDA before reverting to the stock ROM.

**Comment by Donzi84** [comment]
> All regular (i.e., non-GSI) ROMs, including full firmware packs, ship with a kernel.
> The kernel is the core of the operating system.
> Without it, there's no access to the hardware.
> Look for a custom kernel for your device on XDA before reverting to the stock ROM.

Look for a custom kernel means find someone able to modify the kernel of the rom?

Thanks a lot 
Stefano

**Comment by VR-25** [comment]
Either look for a replacement kernel or someone who can fix the charging control issues of the current kernel.

**Comment by Donzi84** [comment]
Hi all,

I found the solution: when you use the batt_slate_mode the  file block the ac charge but not the usb charge. You have to use the file test_mode.

here the values that you have to fill in Battery Charge Limit, Control Charge, or ACC:

/sys/class/power_supply/battery/test_mode
Enable Value: 0
Disable value: 1


Let me know if it works for you.
Stefano
