### ISSUE TITLE
Screen/display will not stay off while charging

### ISSUE THREAD

**Issue by roxy712** [VR-25/acc#123]
Running latest version on a Pixel 4a (Sunfish) with LineageOS 18.1. I installed ACC when I first got the phone about 6 months ago, but there appeared to be an issue with the switches as it wouldn't stop at the defined limit, so I disabled it.

I recently upgraded to the latest version and it appears the switch issue has been fixed, but the phone will not keep its display off while charging with accd running. AOD is disabled, "wake on plug" is on in Android settings (but it's supposed to be "wake for a few seconds, then back to sleep.")

Steps to reproduce:
1) Plug in phone
2) Power off screen via pressing power button
3) Wait 5 seconds. Screen turns on by itself
4) Turn screen off vua power button again
5) Repeat steps 3-4 ad nauseum

The phone will charge to its limit with the screen on, but it obviously takes much longer to do so.

If I disable "wake on plug," he issue goes away and screen stays off. It's more of a convenience issue than anything. Maybe the wakelocks are keeping the screen on?

**Comment by VR-25** [comment]
Install [this](https://github.com/VR-25/acc/files/7696614/acc_v2021.12.11_202112110.zip) build and see if all working charging switches (`acc -t` lists them) trigger this erratic behavior.
