### ISSUE TITLE
Android端末が壊れました。

### ISSUE THREAD

**Issue by s1204IT** [VR-25/acc#125]
このACCをインストールしてから、正常に充電されなくなりました。
再起動しないとバッテリー残量が更新されません。
リカバリーでも同様です。
MagiskからACCをアンインストールしても元に戻りません。
どうしたら直りますか？

**Comment by VR-25** [comment]
[readme > warnings](https://github.com/VR-25/acc#warnings)
[readme > troubleshooting > charging switch](https://github.com/VR-25/acc#charging-switch)
