### ISSUE TITLE
Support A205xx battery idle

### ISSUE THREAD

**Issue by cledsupper** [VR-25/acc#128]
Device: SM-A205G
OS: Android 11 (R) / OneUI 3.1

ACC doesn't seem to support 'battery idle' feature of Galaxy A20.

I even tried adding the sysfs switch file manually on AccA (ACC frontend). While testing, AccA says it works, but ACC can't detect battery stop charging and automatically change to the default charging switch.

I believe this happened because 'status' continue to report that the battery is "Charging", while 'current_now' varies between -10 ~ 10 mA once the charge switch is set to 0.

The file below is part of a program I made to get an equivalent "conservation mode" feature (available on Ideapad 320) to work on my phone. It contains all relevant information.

[battery.sh](https://github.com/cledsupper/batservice-a20/blob/magisk-module/lib/battery.sh)

**Comment by VR-25** [comment]
Working on it.

**Comment by VR-25** [comment]
[acc_v2021.12.3_202112030.zip](https://github.com/VR-25/acc/files/7651938/acc_v2021.12.3_202112030.zip)
Let me know whether this build gets the job done.

**Comment by cledsupper** [comment]
I used the 'acc' command to select the switch and also the charge levels.
But ACC doesn't even seem to touch the 'hmt_ta_charge' file.

**Comment by cledsupper** [comment]
[acc-logs-a20.tar.gz](https://github.com/VR-25/acc/files/7654372/acc-logs-a20.tar.gz)

**Comment by cledsupper** [comment]
Sorry if my actions on this issue make some noise.
I noticed through some thorough research that the logs generated by ACC expose a lot of sensitive data from my device that is unnecessary for service development.
[acc-logs-a20-directorscut.tar.gz](https://github.com/VR-25/acc/files/7654416/acc-logs-a20-directorscut.tar.gz)

**Comment by VR-25** [comment]
Idle mode support will get better.

I'll also work on minimizing the amount of information that is logged and exclude potentially sensitive bits.

Thanks for the input.

**Comment by VR-25** [comment]
[acc_v2021.12.5_202112050.zip](https://github.com/VR-25/acc/files/7655798/acc_v2021.12.5_202112050.zip)

**Comment by cledsupper** [comment]
I don't know if this is an app issue, but AccA is showing the battery is discharging and current is a negative value.

![Screenshot_20211206-153348_AccA](https://user-images.githubusercontent.com/29260339/144902412-b3cf2f04-e40e-4575-b75b-1d1004d5ad79.jpg)

I'll be posting the logs soon.

**Comment by cledsupper** [comment]
[acc-logs-a20-directorscut.zip](https://github.com/VR-25/acc/files/7662935/acc-logs-a20-directorscut.zip)

**Comment by VR-25** [comment]
> [acc_v2021.12.5_202112050.zip](https://github.com/VR-25/acc/files/7655798/acc_v2021.12.5_202112050.zip)

Have you tried this build?

**Comment by cledsupper** [comment]
> > [acc_v2021.12.5_202112050.zip](https://github.com/VR-25/acc/files/7655798/acc_v2021.12.5_202112050.zip)
> 
> Have you tried this build?

Yes. I uploaded that logs and image right after testing the build, and it didn't work.

**Comment by VR-25** [comment]
> Yes. I uploaded that logs and image right after testing the build, and it didn't work.

That's weird, considering that the logs contain v2021.12.3, dmesg.txt and a prop file with sensitive information.
The new version does not have any of that.

**Comment by cledsupper** [comment]
> > Yes. I uploaded that logs and image right after testing the build, and it didn't work.
> 
> That's weird, considering that the logs contain v2021.12.3, dmesg.txt and a prop file with sensitive information. The new version does not have any of that.

Maybe AccA had installed an old build again. I'm going to test it one more time.

**Comment by cledsupper** [comment]
Mistake was mine. When selecting the zip file, I didn't paid attention for the file selector opened in another directory

**Comment by cledsupper** [comment]
ACC seems to read the charge status inverted. But I can't opine on this as I haven't studied the source code.

[acc-logs-a20.tar.gz](https://github.com/VR-25/acc/files/7665773/acc-logs-a20.tar.gz)

**Comment by VR-25** [comment]
> ACC seems to read the charge status inverted. But I can't opine on this as I haven't studied the source code.
> 
> [acc-logs-a20.tar.gz](https://github.com/VR-25/acc/files/7665773/acc-logs-a20.tar.gz)
> 

I'll have a look at the logs later.
Meanwhile, see if you can pinpoint issues in `acc/batt-interface.sh`.

**Comment by VR-25** [comment]
[acc_v2021.12.11_202112110.zip](https://github.com/VR-25/acc/files/7696614/acc_v2021.12.11_202112110.zip)
Try this.

**Comment by cledsupper** [comment]
Great!

But now ACC crashes, at least according to AccA app.

[acc-logs-a20.tar.gz](https://github.com/VR-25/acc/files/7699142/acc-logs-a20.tar.gz)

**Comment by VR-25** [comment]
[acc_v2021.12.12_202112120.zip](https://github.com/VR-25/acc/files/7699211/acc_v2021.12.12_202112120.zip)

**Comment by cledsupper** [comment]
[acc-logs-a20.tar.gz](https://github.com/VR-25/acc/files/7734883/acc-logs-a20.tar.gz)

**Comment by VR-25** [comment]
How about [this](https://forum.xda-developers.com/attachments/acc_v2021-12-15-1_202112151-zip.5485065/) build?

**Comment by cledsupper** [comment]
Now it's working fine!
