### ISSUE TITLE
Charging current limiter works weird on Pixel 5

### ISSUE THREAD

**Issue by mrDoctorWho** [VR-25/acc#129]
I'll go straight to the point:

The phone is connected to it's original USB-C charger. I use `acc -sc` command to limit the current. Current measurements are done via AccuBattery.

1. If the current is limited to 500 milliamps, the real charging current is around 1000 milliamps.
2. If the current is limited to 1000 milliamps, the real charging current is around 1600—1845 milliamps.
3. If the current is limited to 1500 milliamps, the real charging current is around 2600 milliamps.

Is this a normal behavior?

**Comment by VR-25** [comment]
This is a kernel issue.
See if setting _current_workaround=true_ helps: `acc -s current_workaround=true` or `acc -s cw=true`.
You may need to reboot for changes to take effect.
