### ISSUE TITLE
ACC charging switch detection

### ISSUE THREAD

**Issue by yliam73** [VR-25/acc#132]
During the charging switch testing, when it reaches the battery/input_suspend switch, the phone will stop charging but acc reports that the switch does not work even though android shows the correct not charging battery icon, this causes acc to freak out and enable charging randomly. I just went back a few versions and install the 2021 2.25 on cause that always works perfectly for me.

**Comment by VR-25** [comment]
Try [this](https://github.com/VR-25/acc/files/7696614/acc_v2021.12.11_202112110.zip) build.
