### ISSUE TITLE
Xiaomi Renoir issue

### ISSUE THREAD

**Issue by Hogehopo** [VR-25/acc#134]
I'm using Xiaomi's renoir.
The name of CustomRom is FlokoROM.
ACC does not work with this ROM.
Charging does not stop even if the specified charging value is reached.
Attach the Log.
Please tell me what to do.
thank you.
[acc-logs-renoir.tar.gz](https://github.com/VR-25/acc/files/7819832/acc-logs-renoir.tar.gz)

**Comment by Hogehopo** [comment]
Please tell me　(T_T)

**Comment by VR-25** [comment]
You're not using the latest version, my friend.
This is a requirement for reporting issues.
Download and install the [latest](https://github.com/VR-25/acc/releases/latest) flashable zip.
See if the issue persists.
A new release will be available in a few days.

**Comment by Hogehopo** [comment]
> You're not using the latest version, my friend. This is a requirement for reporting issues. Download and install the [latest](https://github.com/VR-25/acc/releases/latest) flashable zip. See if the issue persists.

Thank you for your reply。I tried running the latest version。However, charging does not come beyond the set upper temperature
[acc-logs-renoir0118.tar.gz](https://github.com/VR-25/acc/files/7887466/acc-logs-renoir0118.tar.gz)
。I will attach Log, so please give me some advice

**Comment by Hogehopo** [comment]
The question is, does acc support SD780G?

**Comment by VR-25** [comment]
The actual question is, does your kernel support acc? :)
A new release will be up soon.
