### ISSUE TITLE
CHARGING STATUS BUG

### ISSUE THREAD

**Issue by Emanresult** [VR-25/acc#135]
![Screenshot_20220107-145102](https://user-images.githubusercontent.com/97277554/148505355-148e6dd6-75ee-41fc-88e8-a83ea3291911.png)

I use this module on my rednote 8 pro
Eventhough the plug is disable, the status show its charging
I allready restart the daemon but its won't work

**Comment by VR-25** [comment]
You must disable your system's own battery settings to avoid interference. You can't have those along with acc's.
