### ISSUE TITLE
HELP NEEDED!!

### ISSUE THREAD

**Issue by Emanresult** [VR-25/acc#136]
![Screenshot_20220108-210804_1](https://user-images.githubusercontent.com/97277554/148645450-7ae499bf-ad22-4fad-b0ce-50b6b50bd16b.png)

Anyone how how to fix this?
Charger disable but status charging
Test on Redmi Note 8 Pro

Thanks

**Comment by VR-25** [comment]
This is called ghost charging. It's a kernel problem. Ensure you're running the latest version of acc (released today). ACC has workarounds for this. The daemon must be running to apply them.

**Comment by Emanresult** [comment]
Nah, it make it worse,
I can't even run "acc" now
Maybe my kernel dont compatible for this module,

**Comment by VR-25** [comment]
A new release will be up soon.
