### ISSUE TITLE
Feature request: updateJson attribute for magisk

### ISSUE THREAD

**Issue by v1993** [VR-25/acc#140]
Now that magisk's repository is no longer maintained, modules are expected to define `updateJson` attribute in order to allow updating from withing magisk application. It would be really nice for ACC to utilize this new functionality.

**Comment by VR-25** [comment]
It's already implemented.
You'll see it in the next release, coming up soon.

**Comment by v1993** [comment]
Nice, looking forward to it! Additionally, can you consider submitting to [new module repository](https://github.com/Magisk-Modules-Alt-Repo/submission)? It's maintained by enthusiasts rather than Magisk creator and still in early stages for now, but people are clearly interested in it.

**Comment by VR-25** [comment]
Sure!
