### ISSUE TITLE
OTG get disconnected while acc is running

### ISSUE THREAD

**Issue by R4ygen** [VR-25/acc#149]
Device: OnePlus Nord 2
Charging switch (the only one that works on this device): `/sys/devices/virtual/oplus_chg/battery/mmi_charging_enable 1 0`

I've recently noticed that my OTG devices, like pendrives and otg IR blasters, would get suddently disconnected shortly after connecting them to the phone (like, 1-2 seconds).
I've circumscribed the origin of the issue to ACC. If the acc daemon is turned off, the issue disappears.

Attached log is taken shortly after the OTG device get disconnected by ACC, and then physically disconnected too.
[acc-logs-OP515BL1.tar.gz](https://github.com/VR-25/acc/files/8687315/acc-logs-OP515BL1.tar.gz)

**Comment by VR-25** [comment]
The charging switch itself it to blame. If it's really the only one available, you're out of luck.
Once I get some spare time, I'll see if the logs reveal potential charging switches.
