### ISSUE TITLE
Battery health

### ISSUE THREAD

**Issue by yephny** [VR-25/acc#155]
Can acc tell what my battery's current capacity after a year of use is? I'd like to know if it's below 80% to see whether I should replace it. When I check the `HEALTH` line in `acc --info`, it just says "under voltage", sometimes "good".

**Comment by vonguyenkhang** [comment]
> Can acc tell what my battery's current capacity after a year of use is? I'd like to know if it's below 80% to see whether I should replace it. When I check the `HEALTH` line in `acc --info`, it just says "under voltage", sometimes "good".

Did you see [this article](https://www.gizchina.com/2022/06/15/how-to-check-if-your-xiaomi-device-battery-is-healthy/) before coming here, by any chance?

**Comment by yephny** [comment]
@vonguyenkhang No.

**Comment by vonguyenkhang** [comment]
@yephny have you tried the method in that article? 
> To check the battery health percentage, you need to use a math formula. You need to use the following formula: (actual capacity / current capacity) *100. For example, the formula here considers the Pixel 4 battery of 2,800 mAh. So the math is (2386 / 2800) *100. As a result of the calculation, the battery health is 85 percent, but the data may not be 100 percent accurate. As said before, the most accurate results come with a fully-charged battery.

**Comment by yephny** [comment]
@vonguyenkhang It indeed is a manual method of calculating battery health, which I find to be less accurate than what's reported by certain propriatery apps that take several measurements from below 10% to 100%. Nevertheless, what I am asking for in this issue is not a way to find out my battery's health. I want to know whether acc can or should report battery health in percentage and how the current `HEALTH` information should be used.

**Comment by vonguyenkhang** [comment]
> whether acc can or should report battery health in percentage 

I don't think there's "battery health in percentage" in acc now. In my opinion, it's a good-to-have feature, but with the limited manpower & resources of this project, I prefer acc to stay lean and be more focused on "charging control" than to grow into a proprietary half-baked AIO app.

> and how the current `HEALTH` information should be used.

From [REAME.md](https://github.com/VR-25/acc#the-output-of---info):
> **The Output of --info**
> It comes from the kernel, not acc itself. Some kernels provide more information than others.
> 
> Most of the lines are either unnecessary (e.g., type: everyone knows that already) or unreliable (e.g., health, speed).
> 
> Here's what one should focus on:
> 
> STATUS=Charging # Charging, Discharging or Idle CAPACITY=50 # Battery level, 0-100 TEMP=281 # Always in (ºC * 10) CURRENT_NOW=0 # Charging current (Amps) VOLTAGE_NOW=3.861 # Charging voltage (Volts) POWER_NOW=0 # (CURRENT_NOW * VOLTAGE_NOW) (Watts)
> 
> Note that the power information refers to what is actually supplied to the battery, not what's coming from the adapter. External power is always converted before it reaches the battery.

**Comment by yephny** [comment]
@vonguyenkhang Reporting battery health% would make acc a half-baked AIO app. As for the health info from the command, it is unreliable, so I shouldn't worry about that although it is clearly visible in the overview of AccA. Is this the takeaway from your message? I don't agree with your first point at all. Though, my opinion would change if you were to say that the percentage report would be, at best, speculative, and should never be taken at face value; thus, it wouldn't fit in the app considering how technical and accurate everything is intended to be with acc.

**Comment by vonguyenkhang** [comment]
@yephny 
> Is this the takeaway from your message?

More or less so. I just want to be realistic: at the moment, acc is free & open-source and there's only 1 main developer and a few testers/testing devices, and I wish the development effort is spent more on core features. I'm just an end-user like you, so what I wish may not be the same as the developer's vision.
Regarding your idea about the battery health info shown in the overview of AccA, you should send to AccA developers instead. Maybe they can add the tooltip with the disclaimer there.

**Comment by VR-25** [comment]
Such an enjoyable discussion...

Here are my two cents:

I do focus primarily on the core features (implies compatibility). In fact, my main goal has always been making acc compatible with as many devices as possible. This is the greatest challenge, by far -- especially now that OEMs seem to be stepping on the issue, either directly or indirectly (worsening it).

Additional features...
I implement those that benefit a significant number of users. I do so in a modular fashion, so that all the "elses" and "pluses" are essentially isolated from the core features. The issue in question is on the to-do list.

**Comment by VR-25** [comment]
The latest pre-release calculates battery health% using data from `charge_full` and `charge_full_design`.

**Comment by yephny** [comment]
@VR-25 Does that mean you have to charge your phone to 100% to get a more accurate report?

**Comment by VR-25** [comment]
> @VR-25 Does that mean you have to charge your phone to 100% to get a more accurate report?

Not Necessarily
`charge_full` is the maximum charge the battery can hold now, in contrast with `charge_full_design` (the original charge capacity). `charge_full` is calculated by the battery management system itself, and it's generally fairly accurate.
That said, for calculating `BATT_HEALTH%`, acc uses the formula `(charge_full * 100) / charge_full_design`.
You only ever need to recalibrate the battery management system manually* when those numbers seem weird (too high/low) and remain so across several charging sessions.

* Nowadays, it's smart enough to recalibrate itself. Of course, since things are not perfect in the real world, some miscalculations are expected sometimes.

> You're legendary.

I take that with a grain of salt.

**Comment by yephny** [comment]
How do I use the implemented feature to get the health percentage? `--info`` doesn't have it.

**Comment by VR-25** [comment]
> How do I use the implemented feature to get the health percentage? `--info` doesn't have it.

That feature was dropped, because most devices don't provide reliable data for battery health calculations.

**Comment by VR-25** [comment]
> Noticed there's now the command `acc --health` but it returns `/system/bin/acc -H|--health <mAh>`.

It returns the correct syntax.
e.g., `acc -H 4000`, if you have a 4000 mAh battery.

**Comment by yephny** [comment]
My bad, it works just as expected. Thanks.
