### ISSUE TITLE
lineageos not supported?

### ISSUE THREAD

**Issue by Alanniea** [VR-25/acc#157]
lineageos 18 Charging always power off

**Comment by VR-25** [comment]
This depends on the kernel, not the ROM itself.
Try the latest pre-release.

**Comment by Alanniea** [comment]
The supported kernel version is

> 这取决于内核，而不是 ROM 本身。 尝试最新的预发布版本。



> 这取决于内核，而不是 ROM 本身。 尝试最新的预发布版本。

**Comment by Alanniea** [comment]
> 这取决于内核，而不是 ROM 本身。 尝试最新的预发布版本。

What is the supported kernel version

**Comment by VR-25** [comment]
I would have to get a phone with the same brand and model as yours to know that.
Just try the latest acc pre-release.

**Comment by Alanniea** [comment]
Versions after v2022.2.22.1 cannot be used
