### ISSUE TITLE
Suddenly Doesn't Work

### ISSUE THREAD

**Issue by christantoan** [VR-25/acc#159]
Hello,

I'm having a problem with ACC v2022.6.4 suddenly doesn't work. The only thing I updated today was Shamiko but rolling back its version still doesn't work. I also have tried rolling back ACC to v2022.2.3 but also didn't work.

Some extra info:
I always use "battery/op_disable_charge 0 1 --" because it always worked for me and I want to use Battery Idle mode even though the test sometimes says it doesn't work. One thing I notice is that, in Battery Info page, op_disable_charge is still set to 0 even though it should be set to 1?
I also often have problem with the test because it often loops reporting the current battery status without advancing to the next switch.

[acc-logs-OnePlus7Pro.zip](https://github.com/VR-25/acc/files/9003132/acc-logs-OnePlus7Pro.zip)

Thank you in advance!

**Comment by VR-25** [comment]
new build: https://forum.xda-developers.com/t/advanced-charging-controller-acc.3668427/post-87084881

**Comment by VR-25** [comment]
See if the issues remain.

> When testing switches, I notice that running acc -d also stops accd but acc -e doesn't run accd Is that normal?

This is intended behavior.
Those two commands must stop accd to avoid interference (manual vs automatic modes).

**Comment by christantoan** [comment]
Thanks for the new build. I'll test it for now

**Comment by christantoan** [comment]
Seems to work great now
Thanks!
