### ISSUE TITLE
Temparature control

### ISSUE THREAD

**Issue by pritamdtk** [VR-25/acc#162]
[logs.zip](https://github.com/VR-25/acc/files/9183813/logs.zip)
Temparature control not working on
Device: poco m2 pro
Android 10 stock miui

**Comment by VR-25** [comment]
Wrong configuration, please go with the default settings. Change only what you want to test.

[acc_v2023.7.16_202307160.zip](https://github.com/VR-25/acc/files/12063453/acc_v2023.7.16_202307160.zip)
Try this build.
