### ISSUE TITLE
Question: Stop charging at 81%

### ISSUE THREAD

**Issue by likkai** [VR-25/acc#164]
I'm on miui 13 (Android 12), I'm just wondering why does the phone stop charging when it reaches 81% even though the pause_capacity was set to 86%. It's not a serious problem, I'm just wondering why did it happen. 
![IMG_20220805_173754.jpg](https://user-images.githubusercontent.com/76016664/183050217-6ced7719-a98d-4b0a-8bc8-cc2b78ffbd35.jpg)
![IMG_20220805_173823.jpg](https://user-images.githubusercontent.com/76016664/183050271-708a5193-5957-48b5-8c54-9375ee245023.jpg)

**Comment by ViniciusRed** [comment]
update your acc to the latest version to see if it fixed
[v2022.7.30-dev](https://github.com/VR-25/acc/releases/tag/v2022.7.30-dev)

**Comment by likkai** [comment]
Late reply but yes, it does fix the problem
