### ISSUE TITLE
NOTHING Phone 1 does not pause charge 

### ISSUE THREAD

**Issue by Gamgee16** [VR-25/acc#175]
Hi, i've installed the lastest dev build. I've tried via acc settings and terminal and after the demon started let's with

`acc 70 60`
`accd`

The phone successfully reach 70 but it blocks the charge in what seems like an idle charging because the battery remain at 70  without stopping charging .

**Comment by Bryantdl7** [comment]
You should really add more details

**Comment by VR-25** [comment]
That's called idle mode, a.k.a., charging bypass.
