### ISSUE TITLE
Charging limit unreliable on Pixel 7 Pro

### ISSUE THREAD

**Issue by matejdro** [VR-25/acc#178]
I've been trying to use ACC for a while and charging limit percentage seems very unreliable. Regardless of what switch I use (either one of those that work from the `acc --test` command or native Pixel switch (#124)), charging stop will work at first, but then stop working a while later. It seems like acc disables itself after some time.

Charging current limit seems to work fine, though. At the moment I use acc only for charge current limtiing and manually apply the native Pixel switch on boot (which sticks until next reboot) as a workaround. This works fine, but it would be nice to have everything in one package.

Here are logs after an overnight charge that charged to over my limit of 70%: [Archive.zip](https://github.com/VR-25/acc/files/10312559/Archive.zip)

**Comment by kleops9** [comment]
Did you try to use the latest [v2022.7.30-dev](https://github.com/VR-25/acc/releases/tag/v2022.7.30-dev) Pre-release module? 
I have pixel 6 pro and had the same issue but with the prelease it works.

**Comment by matejdro** [comment]
No, that was on https://github.com/VR-25/acc/releases/tag/v2022.6.4. Will try the prerelease and report, thanks.

**Comment by matejdro** [comment]
Pre-release has been working for the past couple of weeks. Thanks!
