### ISSUE TITLE
MI 11 Ultra wireless charging not stopping

### ISSUE THREAD

**Issue by knasiotis** [VR-25/acc#179]
When I connect a mi 11 ultra to a xiaomi charger with a xiaomi wireless stand, the phone never stops charging. What's interesting is that when I place the phone in the wireless stand, the AccA app shows the phone as "discharging" but I can see the battery percentage increase over time. Now even when I plug the cable it says discharging 
EDIT: after clean uninstalling and reinstall of ACC and AccA, plug charging works ok. Wireless stops at 70% lessay and while it says discharging, it's charging. Does it have to do with the way it stops charging?
This is really confusing: Now when I connect the plug it says discharging but the battery is charging. Doesn't stop after the limit

**Comment by knasiotis** [comment]
I uploaded the logs to your dropbox

**Comment by knasiotis** [comment]
Still shows a negative current btw

**Comment by cubale** [comment]
I have the same problem.

**Comment by VR-25** [comment]
Update [acc]([acc_v2023.7.13-dev_202307130_1925.zip](https://github.com/VR-25/acc/files/12043016/acc_v2023.7.13-dev_202307130_1925.zip)).

**Comment by knasiotis** [comment]
@VR-25 This build works great so far, I tried to save logs but I couldn't reproduce the issue. 
The behavior was (when battery limit was reached):
-Status: discharging
-Wireless stand was active
-Phone was charging above limit
Now it is:
-Status: discharging
-Wireless stand tries to make nfc handshake
-It succeeds for a split second and then stops
-Phone is not charging

So it seems to be working now, I haven't seen the battery going above the limit. I don't have the time to test it extensively but I will inform you when I do it
