### ISSUE TITLE
Very low wattage after resume

### ISSUE THREAD

**Issue by KaMyKaSii** [VR-25/acc#18]
Most of the time, after the resume percentage is reached, the wattage is very low and the battery goes down even with the system reporting that it is charging (but decreasing more slowly than not charging). Unplugging the cable and plugging it in again makes the wattage normalize. Rarely the wattage after acc resuming is decent, I can't tell what the pattern is. The first screenshot is after the acc automatically resumes, the second after unplugging and plugging the cable.
![Screenshot_20191030-131840832](https://user-images.githubusercontent.com/17092335/67881039-85916600-fb1e-11e9-8522-e7c9cbfc4f9c.png)
![Screenshot_20191030-132004320](https://user-images.githubusercontent.com/17092335/67880572-a7d6b400-fb1d-11e9-9b4c-1bf100122e89.png)

[acc-logs-ASUS_Z01KD_3.zip](https://github.com/VR-25/acc/files/3790256/acc-logs-ASUS_Z01KD_3.zip)

**Comment by VR-25** [comment]
Upgrade to the [latest release](https://github.com/VR-25/acc/releases) and test with different charging switches `acc -s s`.

**Comment by KaMyKaSii** [comment]
> Upgrade to the [latest release](https://github.com/VR-25/acc/releases) and test different charging switches (`acc -s s`).

The only one that works is battery/input_suspend
[acc-logs-ASUS_Z01KD_3(1).zip](https://github.com/VR-25/acc/files/4005672/acc-logs-ASUS_Z01KD_3.1.zip)
