### ISSUE TITLE
Charge current limit non-functional under Mi 11 Lite NE (lisa)

### ISSUE THREAD

**Issue by Iey4iej3** [VR-25/acc#181]
The charge current limit does not work under `lisa`, latest 2022-07-30 build

The log files are attached (I touched `magisk.log` to suppress the denylist which might contain some sensitive information)
[acc-logs-lisa.zip](https://github.com/VR-25/acc/files/10499930/acc-logs-lisa.zip)

**Comment by VR-25** [comment]
Not all devices/kernels support this.
Refer to #182 for a workaround.

**Comment by Iey4iej3** [comment]
Just a sidenote: `temp_level` does not work on lisa.

**Comment by VR-25** [comment]
It only works on devices that have `temp_level` or `siop_level` files control files - and whose kernels allow such tweaks.
