### ISSUE TITLE
How to set max charging Voltage using Fast charger(PD, QC etc) to 9V?

### ISSUE THREAD

**Issue by ellegance** [VR-25/acc#189]
From official ACC documentation:
 -s|--set v|--voltage [millivolts|-] [--exit]   Set/print/restore_default max charging voltage (range: 3700-4300 Millivolts)
 -s|--set c|--current [milliamps|-]   Set/print/restore_default max charging current (range: 0-9999 Milliamps)

Modern phone support chargers which use 20V and ~6.5A. While 9.99A limit in ACC is understandable, 4.3V seems to be low.
1. What ACC commands should be run after installation of ACC in order to restrict fast charging at maximum of 9V and 3A (27W)?
2. What ACC commands should be run (cooldown above/ charge below/ pause above) in order to set Maximum charge percentage to 90%?

Thanks

**Comment by JeelsBoobz** [comment]
Edit file on ```set-ch-volt.sh```

**Comment by worstperson** [comment]
Afaik, acc controls charging between the charge controller and battery. So voltage will be battery voltage and current will be charge current. The phone can negotiate a higher voltage with the charger so more watts can be transferred through the same wire, but that voltage will be reduced down through a buck regulator before it reaches the battery.

You'd probably need to patch your kernel if you want to limit pd negotiation to 9v, but I don't know why you would. Setting current around 6400 and pause_capacity to 90 should do what you want more or less.

**Comment by VR-25** [comment]
> Afaik, acc controls charging between the charge controller and battery. So voltage will be battery voltage and current will be charge current. The phone can negotiate a higher voltage with the charger so more watts can be transferred through the same wire, but that voltage will be reduced down through a buck regulator before it reaches the battery.
> 
> You'd probably need to patch your kernel if you want to limit pd negotiation to 9v, but I don't know why you would. Setting current around 6400 and pause_capacity to 90 should do what you want more or less.

That's the answer.

While modifying the raw input current/voltage is possible on some devices (look for "Pixel" in the readme), it's not the focus of this software.
