### ISSUE TITLE
Oneplus 7t pro  kernel how to enable support battery idle ?

### ISSUE THREAD

**Issue by sdandroid** [VR-25/acc#19]

**Comment by VR-25** [comment]
Generally, power drivers may have to be modified.
I'm yet to take a closer look at this device's power supply log, though.

**Comment by sdandroid** [comment]
log file [acc-logs-OnePlus7TPro.zip](https://github.com/VR-25/acc/files/3963950/acc-logs-OnePlus7TPro.zip)

**Comment by VR-25** [comment]
Battery idle mode is supported by the charging switch `battery/op_disable_charge 0 1`.
It's already available in OOS Beta.
Some custom kernel devs have eyes on that.
You just have to wait a bit.
