### ISSUE TITLE
Redmi Note 9, LineageOS 20

### ISSUE THREAD

**Issue by Dramorian** [VR-25/acc#191]
A switch (the only valid one) works, charging stops but doesn't disconnect after reaching the threshold (no unplug sound).
Is there a workaround for this?

**Comment by Iey4iej3** [comment]
It is better to have a log. See https://github.com/VR-25/acc/issues/5

**Comment by VR-25** [comment]
> A switch (the only valid one) works, charging stops but doesn't disconnect after reaching the threshold (no unplug sound). Is there a workaround for this?

`acc -s cs=true` (default: auto)
With this, acc will control Android's battery service.
There will be a few seconds delay between battery status/level updates, though -- for the sake of efficiency.
