### ISSUE TITLE
Redmi Note 5, LineageOS 18

### ISSUE THREAD

**Issue by jotkauser** [VR-25/acc#193]
When i installed ACC my phone randomly thinks its charging and vice versa, and annoying sound, how to fix

**Comment by Iey4iej3** [comment]
It is better to have a log, see https://github.com/VR-25/acc/issues/5

**Comment by VR-25** [comment]
[acc_v2023.7.16_202307160.zip](https://github.com/VR-25/acc/files/12063453/acc_v2023.7.16_202307160.zip)
Try this build.
