### ISSUE TITLE
Module Disapears on Reboot

### ISSUE THREAD

**Issue by Muteplayer** [VR-25/acc#194]
I'm using KernelSU as root solution, and it support modules like Magisk but with some diferences. When I installed this module and rebooted, the module desapears, and left the folder in ```/data/adb/vr25/```.
[Logs](https://send.jeugdhulp.be/download/977706b35e453970/#7UzZa3t_Ie5oTAgDKspNRA)

**Comment by ViniciusRed** [comment]
Try to install using the terminal and see if it gives the same problem

**Comment by VR-25** [comment]
No longer facing this issue? What did you do to overcome it?

**Comment by VR-25** [comment]
There's a second report on this.
I'm working on it.

**Comment by VR-25** [comment]
#197
