### ISSUE TITLE
voltFactor doesn't work

### ISSUE THREAD

**Issue by bober757** [VR-25/acc#195]
acc v2022.7.30-dev
acca v1.0.35
OnePlus 7, LineageOS 20-20230605, Android 13

any value of voltFactor doesn't matter. tried 1 000; 1 000 000; 10 000 000. then charging and discharging. output is same
![Screenshot_20230610-075354_AccA](https://github.com/VR-25/acc/assets/97284661/90b8cc1c-d6d2-462f-a1e2-f859714ab2f1)

acc --info
`
Battery Service

  AC powered: false
  USB powered: false
  Wireless powered: false
  Max charging current: 0
  Max charging voltage: 0
  Charge counter: 2849000
  status: 3
  health: 2
  present: true
  level: 77
  scale: 100
  voltage: 3985
  temperature: 294
  technology: Li-ion

Uevent

  ADAPTER_FW_UPDATE=0
  AUTHENTICATE=1
  BATTERY_TYPE=alium_860_89032_0000_3600mah_sept24th2018
  BATT_AGE_LEVEL=-22
  BATT_CC=0
  BATT_FCC=2123
  BATT_RM=1522
  BATT_SOH=823
  CALIBRATE=-22
  CAPACITY=76
  CAPACITY=76
  CAPACITY_RAW=185
  CC_SOC=-8161
  CC_STEP=0
  CC_STEP_SEL=0
  CHARGERID_VOLT=0
  CHARGER_TEMP=-1
  CHARGER_TEMP_MAX=-1
  CHARGE_CONTROL_LIMIT=0
  CHARGE_CONTROL_LIMIT_MAX=4
  CHARGE_COUNTER=2535012
  CHARGE_COUNTER=2812000
  CHARGE_COUNTER_SHADOW=2535150
  CHARGE_DONE=0
  CHARGE_FULL=3492000
  CHARGE_FULL_DESIGN=3588000
  CHARGE_NOW=0
  CHARGE_NOW_RAW=-2928450
  CHARGE_TECHNOLOGY=1
  CHARGE_TERM_CURRENT=310
  CHARGE_TIMEOUT=0
  CHIP_SOC=76
  CLEAR_SOH=0
  CONSTANT_CHARGE_CURRENT_MAX=4000000
  CONSTANT_CHARGE_VOLTAGE=4339850
  COOL_DOWN=0
  CURRENT_AVG=218137
  CURRENT_MAX=0
  CURRENT_NOW=169
  CURRENT_NOW=345214
  CURRENT_QNOVO=-22
  CYCLE_COUNT=18
  CYCLE_COUNTS=22 29 27 22 21 19 8 0 
  DEBUG_BATTERY=0
  DIE_HEALTH=Unknown
  DP_DM=0
  ESR_ACTUAL=0
  ESR_NOMINAL=0
  FASTCHARGER=0
  FAST_CHARGE=0
  FCC_STEPPER_ENABLE=0
  FORCE_RECHARGE=0
  HEALTH=Good
  INPUT_CURRENT_LIMITED=0
  INPUT_CURRENT_SETTLED=0
  INPUT_SUSPEND=0
  MMI_CHARGING_ENABLE=1
  NOTIFY_CODE=0
  PARALLEL_DISABLE=0
  POWER_AVG=24819380
  POWER_NOW=35548501
  PRESENT=1
  REAL_CAPACITY=72
  RECHARGE_SOC=98
  RERUN_AICL=0
  RESISTANCE=369873
  RESISTANCE_ID=99700
  SCALE_MODE_EN=0
  SET_SHIP_MODE=0
  SHIP_MODE=0
  SHORT_C_BATT_LIMIT_CHG=0
  SHORT_C_BATT_LIMIT_RECHG=0
  SHORT_C_HW_FEATURE=0
  SHORT_C_HW_STATUS=1
  SHORT_IC_OTP_STATUS=1
  SHORT_IC_OTP_VALUE=0
  SHORT_IC_VOLT_THRESH=0
  SOC_REPORTING_READY=1
  SOH=0
  STATUS=Discharging
  STEP_CHARGING_ENABLED=1
  SW_JEITA_ENABLED=0
  TECHNOLOGY=Li-ion
  TEMP=242
  TEMP=313
  TIME_TO_EMPTY_AVG=26598
  TIME_TO_FULL_AVG=-1
  TIME_TO_FULL_NOW=-1
  VOLTAGE_AVG=3937334
  VOLTAGE_MAX=4390000
  VOLTAGE_MAX_DESIGN=4350000
  VOLTAGE_MIN=3939000
  VOLTAGE_NOW=3907948
  VOLTAGE_NOW=3939000
  VOLTAGE_OCV=4029547
  VOLTAGE_QNOVO=-22
  VOOCCHG_ING=0
  
  CURRENT_NOW=-0.17 Amps
  VOLTAGE_NOW=39079481.00 Volts
  POWER_NOW=-6643510.00 Watts

`

sorry for my english

**Comment by VR-25** [comment]
Fixed!
Upgrade to the latest snapshot by running `acc -u -f dev`
