### ISSUE TITLE
[feature-request] Make it possible to send multiple notifications with `acc -n`

### ISSUE THREAD

**Issue by tamas646** [VR-25/acc#204]
The current behavior of `acc --notif` is that if there's been a notification already showed, it will overwrite it and because of this the previous notification will be lost.

There could be an option to create an independent notification (maybe by giving a custom id or something) which does not overwrite the already shown notification.

**Comment by VR-25** [comment]
Done!
You can pull the latest commits with `acc -u dev`.
Reverting to the previous build and config is as simple as running `acc -b`.
