### ISSUE TITLE
How to always charge 100%?

### ISSUE THREAD

**Issue by realchandan** [VR-25/acc#212]
Hi there,

I have read the readme and I have set pause capacity (`acc -s pc=100`) but the issue I'm having is my phone randomly stops charging at some percentage often it's 28%.

Then I have to manually go to termux and set "Charge once to #%" option to 100

My phone (Xiaomi Redmi Note 8) is old so I don't really care about the battery, I got it repaired and the service center installed I believe a faulty charge controller not made for this phone and without acc the phone charges at much higher voltage/current, thus I only use acc to limit the charging voltage/current.

My queries are -

1. Is there a way to always charge to 100%?
2. When I do `acc` and then press `7` and manually enter `100` I often see "Terminated" being printed out, why is that?

**Comment by VR-25** [comment]
What's your voltage limit?
Limiting voltage also limits capacity/level (because, physics).
A very low limit is the most likely cause of this "issue".

**Comment by realchandan** [comment]
My voltage limit was 3800, Maybe that was an issue?

**Comment by VR-25** [comment]
Most likely, yes.
