### ISSUE TITLE
Need help, not working on Realme X

### ISSUE THREAD

**Issue by JoeNirvana** [VR-25/acc#22]
Probably because it use OPPO VOOC charge, any solution?
Kernal source is here:[https://github.com/realme-kernel-opensource/realmeX-kernel-source](url)

**Comment by VR-25** [comment]
Hi,
I need specific information provided by acc itself (logs).
Please refer to issue #5 for details.
Thanks

**Comment by JoeNirvana** [comment]
Thanks for help.
When i test it using acca, it seems like ctl file doesn't work.
[acc-logs-RMX1901.tar.zip](https://github.com/VR-25/acc/files/3992013/acc-logs-RMX1901.tar.zip)

**Comment by luckydevil13** [comment]
more logs from relame x2
[acc-logs-RMX1991CN.tar.bz2.zip](https://github.com/VR-25/acc/files/4281140/acc-logs-RMX1991CN.tar.bz2.zip)
