### ISSUE TITLE
Option "Screen always on when charging" will stop working when ACC halts charging

### ISSUE THREAD

**Issue by GhostScript0r** [VR-25/acc#220]
I have set the upper charge limit of 85% on my device (Samsung SM-P610) since I almost always keep the devices connected. When ACC halts charging when battery level reaching 85%, the devices' USB connectivity (ADB etc) still works but the screen will turn off like when the device is not connected.

**Comment by VR-25** [comment]
Looks like that feature only works when the battery is actually charging. Or perhaps it also does when the device is in charging bypass mode. For that, you need a switch that supports it. Incorporate the latest development changes with `acc -u dev` and test charging switches with `acc -t`. Look for one that has `battIdleMode=true` and set it with `acc -ss`.
