### ISSUE TITLE
/system/bin/sh: acc: inaccessible or not found

### ISSUE THREAD

**Issue by Willie30F** [VR-25/acc#221]
Can't access acc from Termux anymore, it worked fine a while ago, like a week ago or so. I don't know what happened since then. I am running the latest version of acc (installed through Magisk) on a Pixel 8 Pro with A14 and Magisk 26.4.

Termux output:
`$ su -c acc
/system/bin/sh: acc: inaccessible or not found`

Termux has su rights, even if I su first and then acc it doesn't work.

Looks like I'm not the only one with this problem as several other people on your telegram chat have the same problem.

**Comment by JaHIY** [comment]
The `acc` file is actually located at `/data/adb/modules/acc/acc.sh`.

**Comment by Willie30F** [comment]
> The `acc` file is actually located at `/data/adb/modules/acc/acc.sh`.

It is, but its supposed to be linked as it always was. Looks like it has been fixed with the latest dev. I'll try it out.

**Comment by Willie30F** [comment]
Fixed with [v2023.11.26.1-dev (202311261)](https://github.com/VR-25/acc/commit/509eafa951a9fff33da3c72d1a306ae14ad82bd7). Thanks 👍🙂
