### ISSUE TITLE
Constant audible "discharge_polarity set successfully!" notifications

### ISSUE THREAD

**Issue by schmorp** [VR-25/acc#222]
After upgrading to magisk 26.4 (which might be incidental), I now get constant (about once per second) audible notifications saying "discharge_polarity set successfully!". Rebooting, restarting nor downgrading AccA to an older version help. It worked mostly fine before on my phone.

**Comment by VR-25** [comment]
Se if the latest development build fixes that. Upgrade with `acc -u dev`.

**Comment by VR-25** [comment]
If the above doesn't update, you can flash the zip: https://github.com/VR-25/acc/files/13503603/acc_v2023.11.26.1-dev_202311261_2133.zip

If the issue persists, try a full acc reset (`acc -sr a`) and reboot.
