### ISSUE TITLE
some weird bug

### ISSUE THREAD

**Issue by Yazed-Hasan** [VR-25/acc#225]
it shows charging even i not plug the charger

**Comment by VR-25** [comment]
Paste and run: `acc -u dev; acc -s dp=`

**Comment by Yazed-Hasan** [comment]
> Paste and run: `acc -u dev; acc -s dp=`

:/data/data/com.termux/files/home # acc -u dev; acc -s dp=

################################################################################# 100.0%

################################################################################# 100.0%

No update available

**Comment by VR-25** [comment]
Didn't you get a notification about discharge_polarity?

**Comment by Yazed-Hasan** [comment]
> Didn't you get a notification about discharge_polarity?

yes i did

**Comment by Yazed-Hasan** [comment]
> > Didn't you get a notification about discharge_polarity?
> 
> yes i did

![Screenshot_20231203-155709_Chrome](https://github.com/VR-25/acc/assets/108896411/7b1b790f-d4ea-44aa-ba1b-8f9bc283adf1)

**Comment by Yazed20** [comment]
> Didn't you get a notification about discharge_polarity?

still viewing charging bro

**Comment by VR-25** [comment]
Upgrade to the latest development build and reset discharge polarity.
This can be done with a single command line: `acc -u dev; acc -s dp=`.
