### ISSUE TITLE
Install then unroot?

### ISSUE THREAD

**Issue by silajim** [VR-25/acc#227]
I have rooted the phone, but due to the root shenanigans these latest days I want to unroot the phone but keep this functionality, can I do it? Is it even possible?

**Comment by IslamAlorabI** [comment]
You can use a custom rom that has a **charging control** feature. like : **crdroid** - I think all roms have that feature

![Screenshot_20231208-195617_crDroid Settings.png](https://github.com/VR-25/acc/assets/51124058/e7f44721-500d-4b3f-a572-079e736c4657)

**Comment by silajim** [comment]
I am not using a custom rom, so I don't have that feature, or access to it

**Comment by VR-25** [comment]
This can be achieved with a kernel/ramdisk modified to run acc initialization script (`/data/adb/vr25/acc/service.sh`) on boot.
Ping a kernel dev.
