### ISSUE TITLE
Can't access acc from termux

### ISSUE THREAD

**Issue by 9M2PJU** [VR-25/acc#231]
Installed acc on begonia but can't access from termux

![Screenshot_2023-12-10-02-03-27-598_com.termux.jpg](https://github.com/VR-25/acc/assets/991353/2beaf9e5-e0be-4c41-8554-410e70eb2f19)

**Comment by VR-25** [comment]
Have you tried after rebooting?

If the issue persists, try https://github.com/VR-25/acc/files/13758299/acc_v2023.11.26-dev_202311260_1001.zip

**Comment by jcchikikomori** [comment]
Not working on my end
