### ISSUE TITLE
Suggestion:  Take over scheduling for new "charging control" battery optimization in Android

### ISSUE THREAD

**Issue by ghost** [VR-25/acc#232]
So it seems there's a new charge limiting feature in Android with version 13 I think and I suspect it will become a standard thing for all versions from now on probably.  I'm not sure if this is available to all Android devices (I'm using a Pixel 4a 5G, but I'm on LineageOS rather than stock,) but this has potential to work with the system in a more official fashion and thus work on virtually any phone where the OS implements it which might possibly include anything on a clean OS (aka not Samsung stock probably -- I read it has its own optimization option that may not work well.)  In my settings I have an option labeled "charging control" that is supposed to "automatically determine when to start charging based on alarms set."  I didn't realize how extreme this really was until I noticed that after a few days plugged in it starts to actually lower the battery on purpose and then keep it on 80% from then on.  Apparently it tries to predictively learn your schedules based on alarms and when you use it, but unfortunately will once again charge to 100% if you use it more than a few minutes off the charger or if something like an alarm triggers it.

I was thinking that if something could override the scheduling so it thinks it should _always_ be in charging optimized mode (even when there are alarms) then this would provide a slightly less hacky means of working with the system's more standardized means of limiting charge.  Basically just trick its built in schedule into thinking there are no alarms even if there are and that it should enter battery optimization immediately upon reaching 80%.  Normally it charges back to 100% the moment you plug it back in after optimization goes off from usage or an alarm, so it would need to also trick it into immediately entering optimization mode.

Not sure how well this would work or if it's even possible (or even if applicable) but it seems like if it did work it could make for a more universal solution on perhaps a larger range of devices if it's as universal as it seems like it _should_ be.  Food for thought anyway.

**Comment by VR-25** [comment]
I'm closely following the evolution of this feature and thinking about the possibilities...
