### ISSUE TITLE
Daemon stopped with exit code 7 on a Fresh Install of Xiaomi HyperOS

### ISSUE THREAD

**Issue by ashwinprakas** [VR-25/acc#234]
Daemon stops with exit code 7 on a Fresh Install of Xiaomi HyperOS(A14), was working perfectly fine on the MIUI(A13) and AOSP(A14) roms.
I tried to generate logs but didn't get a response.
*Sometimes even after the above message Daemon remains active and when crossing pause % just shuts down the phone.

**Comment by VR-25** [comment]
I'm also running HyperOS and acc is working.

Try pulling the latest snapshot by running `acc -u -f dev`.

If the command fails and you stumble upon a curl error...

https://github.com/Zackptg5/Cross-Compiled-Binaries-Android/raw/master/curl/curl-arm64

Download that binary, rename to curl, create the directory /data/adb/vr25/bin/, place the file there and set permissions to 755.

**Comment by ashwinprakas** [comment]
Error on my part.

'Nighttime Charging Protection' was ON and it was causing the issue, after disabling it, ACC Settings works as expected.

**Comment by pannal** [comment]
> Download that binary, rename to curl, create the directory /data/adb/vr25/bin/, place the file there and set permissions to 755.

When using that binary, it can't resolve hostnames (raw.githubusercontent.com for example).
