### ISSUE TITLE
Battery Idle mode enabled

### ISSUE THREAD

**Issue by astroskyoffical** [VR-25/acc#235]
Phone: OnePlus 8t
Rom: evolution X 
Rooted: yes
  
I read about idle mode and I think it would be useful to have working.   I have a feeling it's a feature this phone could support and I'm not sure how I go about enabling it.      I have charging control in my settings and it lets me limit how high I can charge my phone but not sure if that's the same thing?  I basically want to be able game and it switch to power brick only the. When I stop it goes back to normal battery.

Any advice?

**Comment by VR-25** [comment]
[acc.zip](https://github.com/VR-25/acc/files/14025722/acc.zip)

Install the latest acc development build either by running acc -u -f dev or flash the zip above.

Turn off your ROM's own charging limit feature.
Run acc -t. You should see battIdleMode=true for at least 1 switch. Generally, no switch setup is needed. But if you really want to select a specific one, run acc -ss.

**Comment by VR-25** [comment]
Newer build: https://github.com/VR-25/acc/files/14069231/acc_v2024.1.26-rc_202401260.zip
