### ISSUE TITLE
Acc reporting non-sensical current, and multiple switches stopped working

### ISSUE THREAD

**Issue by WyntrHeart** [VR-25/acc#236]
A few weeks ago acc was working correctly and I was using the switch "battery/charging_enabled" which worked and allowed idle mode. I remember testing all switches and seeing at least two with idle mode working.

Some time in the last few weeks this just stopped working, without me making any changes to my phone, acc, or anything in Termux. Now when I check the battery status info or test switches all of the ampere measurements are wildly inflated, showing charge *and* discharge rates over 4 amps, despite the phone appearing to actually charge and discharge at its normal rate. And the switch I was previously using with idle mode is no longer working *at all*, and of the three switches that still work none of them support idle mode, which is an essential feature for me.

I don't even know where to start to diagnose this, any ideas?

**Comment by VR-25** [comment]
Upgrade to the latest build and see whether the issue persists.
You can do that directly with `acc -u dev` or by flashing the zip:
[acc_v2024.1.26-rc_202401260.zip](https://github.com/VR-25/acc/files/14069231/acc_v2024.1.26-rc_202401260.zip)

**Comment by WyntrHeart** [comment]
I already tried "acc -u". Adding "dev" to the command gets me the following output:
```
curl: option --dns-servers: the installed libcurl version doesn't support this
curl: try 'curl --help' or 'curl --manual' for more information

No update available
```

**Comment by VR-25** [comment]
Flash the zip.

**Comment by WyntrHeart** [comment]
The zip installed without any issues. The amp measurements are fixed, but I haven't had time to test the switches yet. I'll let you know when I do

**Comment by WyntrHeart** [comment]
Both the amp readings and the switches are working fully. Thank you for the help!

Any idea what I might have messed up to cause this issue to appear?

**Comment by VR-25** [comment]
Could have been an issue related to the build you were running.
