### ISSUE TITLE
Fast charging & Mar 2024 update

### ISSUE THREAD

**Issue by suddenlydoomy** [VR-25/acc#241]
Fast charging doesn't seem to work after installing the Mar 2024 Android update for v2023.10.16.

Disabling the ACC module in Magisk and rebooting enables fast charging.

**Comment by VR-25** [comment]
The latest version is 2024.2.25-rc. Is that what you're running?

**Comment by suddenlydoomy** [comment]
If this is correct, then I sincerely apologize for wasting your time.  But GitHub says that the latest version is v2023.10.16.

Where is this release candidate?

**Comment by VR-25** [comment]
[acc_v2024.2.25-rc_202402250_1841.zip](https://github.com/VR-25/acc/files/14530877/acc_v2024.2.25-rc_202402250_1841.zip)

Usually, those builds are published only on telegram.
Anyone can upgrade to the latest development build by running `acc -u dev`.

**Comment by suddenlydoomy** [comment]
Still experiencing the same issue with that build.

**Comment by VR-25** [comment]
Share your config (`acca - sp`).

**Comment by suddenlydoomy** [comment]
Never mind.  It was a problem with another Magisk install.  I apologize for wasting your time.
