### ISSUE TITLE
resetBsOnPause and resetBsOnUnplug not working on Pixel 8 / Android 14

### ISSUE THREAD

**Issue by WakoKnight** [VR-25/acc#244]
I enabled resetBsOnPause and resetBsOnUnplug using ACC Settings and ACC App, but the battery usage is not resetted. I still see the graph/infos for the past days even after a reboot. Is this related to the latest Android version ?

**Comment by VR-25** [comment]
Yes, this is an issue from Android's side.
Looking for workarounds.
