### ISSUE TITLE
damon stopped with exit code 1 pixel 8 A14

### ISSUE THREAD

**Issue by nutpantz** [VR-25/acc#251]
stops every time in lees then two minutes
i assume the logs are all the same but here are 4 logs

a14 pixel 8 pro

**Comment by nutpantz** [comment]
[logs.zip](https://github.com/VR-25/acc/files/15057774/logs.zip)


ill try the one you posted in the other  issues  

acc_v2024.4.17-rc_202404170_2102   

it also crashed, but did not pop up with a log. 
so i tried 22-06-04 and it is not crashing after 5 minutes. so i hope its working
i will report back with any issues

**Comment by VR-25** [comment]
Try the following build:
[acc_v2024.4.22-rc_202404220_2049.zip](https://github.com/VR-25/acc/files/15068041/acc_v2024.4.22-rc_202404220_2049.zip)

**Comment by nutpantz** [comment]
it ha not crashed yet 
acca is not showing the charging speed (but is showing it is charging)
temp is -1c/30.2f  (which is wrong)
voltage is 0
health unknown.   
  
i had acca set to stop at 83%
 at 82 % i got a system notification that charging was "protecting my battery" and charging stopped.

i have adaptive charging turned off in system settings. 
 
 
so i think it is working. or at least it did not crash at all.
ill test some more. and report back if anything changes or i have more info.

**Comment by VR-25** [comment]
Nice.
Now, could you share a fresh log archive to see what's behind the incorrect reports (current, voltage, etc.)?

**Comment by nutpantz** [comment]
[acc-logs-husky_2024-04-23_04:43:38.tgz](https://github.com/VR-25/acc/files/15076269/acc-logs-husky_2024-04-23_04.43.38.tgz)


These help?

**Comment by VR-25** [comment]
Yes.
I'll take a look soon.

**Comment by nutpantz** [comment]
Another fresh log with latest from my pixel 6
[acc-logs-oriole_2024-04-27_08:41:03.tgz](https://github.com/VR-25/acc/files/15138737/acc-logs-oriole_2024-04-27_08.41.03.tgz)

(Fit the lack of charging details)

**Comment by nutpantz** [comment]
And another fresh from my pixel 8pro
[acc-logs-husky_2024-04-27_08:34:52.tgz](https://github.com/VR-25/acc/files/15138740/acc-logs-husky_2024-04-27_08.34.52.tgz)


Anything else i can do to help. Just let me know

**Comment by VR-25** [comment]
It's now an AccA's own fault.
If you run acc -i, you'll see charging details.

Perhaps I'll think of workarounds for the outdated AccA.

**Comment by nutpantz** [comment]
Is acca abandoned?
Should i make a bug issue there so people know?

**Comment by VR-25** [comment]
The developer stopped supporting it over two years ago.

**Comment by nutpantz** [comment]
I was hoping it was still supported.
I'll make a bug issue there
And hopefully someone interested will fork it

It's not a big deal for me, i just need the charging to stop and start correctly. 
(And a way to test settings)

Thanks for all your work.

**Comment by VR-25** [comment]
Here's a new build: [acc_v2024.5.11-rc_202405110_1223.zip](https://github.com/VR-25/acc/files/15282648/acc_v2024.5.11-rc_202405110_1223.zip)
