### ISSUE TITLE
"Charge once" becomes permanent until restarting acc

### ISSUE THREAD

**Issue by Iey4iej3** [VR-25/acc#253]
ACC version: 2023.10.16

Each time I use "charge once", it seems that the charge limit becomes that number, instead of being once. It could be fixed by restarting the acc daemon.

**Comment by VR-25** [comment]
Install the latest development build.
Try upgrading with `acc -u dev`.
If it doesn't roll, flash the zip below.
[acc_v2024.4.26-rc_202404260_0003.zip](https://github.com/VR-25/acc/files/15137601/acc_v2024.4.26-rc_202404260_0003.zip)

**Comment by VR-25** [comment]
[acc_v2024.5.11-rc_202405110_1223.zip](https://github.com/VR-25/acc/files/15282648/acc_v2024.5.11-rc_202405110_1223.zip)

**Comment by VR-25** [comment]
[acc_v2024.5.11-rc_202405110_1223.zip](https://github.com/VR-25/acc/files/15282648/acc_v2024.5.11-rc_202405110_1223.zip)
