### ISSUE TITLE
acca crashes with latest build

### ISSUE THREAD

**Issue by nutpantz** [VR-25/acc#256]
https://github.com/VR-25/acc/files/15282648/acc_v2024.5.11-rc_202405110_1223.zip

With this installed
Acca crashes instantly, tried clearing cache and stora ge.

I understand acca is not your app, so it's not really an issue for your app. But s large number of people who use your app come from acca (which is no longer supported) and they will all be very confused.
I'll test the simple front end.
And report of i have any issues.
Tested with pixel 6 and 8 pro Android 12 and 14
(Simple front end also crashes when menu settings is selected)

**Comment by VR-25** [comment]
Those apps rely on legacy workarounds that are no longer avaliable. Developers must update them to work with recent versions of acc.

Meanwhile, there's a new front-end in town: https://xdaforums.com/t/advanced-charging-controller-acc.3668427/page-272#post-89486552

**Comment by nutpantz** [comment]
A addon for a paid app?

Thanks for your work
