### ISSUE TITLE
[le zl1] Sometimes charging icon stuck on & battery saver stuck disabled

### ISSUE THREAD

**Issue by jesse-git** [VR-25/acc#28]
I also uploaded power supply log for device le_zl1 on the dropbox.  generally ACC works okay, but roughly around 2 of every 5 times when charging, when the charge stops at the designated percent, a weird thing happens:

* lightning bolt charge icon remains
* battery saver mode will not re-engage, automatically or manually

But it consistently fixes itself  upon reboot.  It happens on:

* RR-P-v7.0.2-20190710-zl1-Official  with Black Screen kernel 6.6.1
* aicp_zl1_p-14.0-WEEKLY-20191226

attached are the logs after  charging to 80 % then discharging to about 67 %
[acc-logs-le_zl1 2020-03-10.zip](https://github.com/VR-25/acc/files/4315468/acc-logs-le_zl1.2020-03-10.zip)

**Comment by VR-25** [comment]
Hi,

1. Install the [latest](https://github.com/VR-25/acc/releases/) pre-release. It's stable enough for daily use.

2. Run `acc -t --` to see which charging switches work.

3. Enforce a working switch with `acc -s s`.

4. Test its reliability and repeat steps 3 and 4 as needed. For details on why this procedure is recommended, refer to https://github.com/VR-25/acc/blob/dev/README.md/#charging-switch .

**Comment by jesse-git** [comment]
read through it, unfortunately did not help

```
# acc --version

2020.3.14-dev (202003140)
# acc -t --
(!) [dc/charging_enabled 1 0] won't work                      
(!) [parallel/charging_enabled 1 0] won't work                
(i) [battery/charging_enabled 1 0] works                      
- battIdleMode=false                                          
(!) [battery/battery_charging_enabled 1 0] won't work
(!) [battery/input_current_settled 0 1] won't work
```
switch_delay was default 1.5
`acc -s switch_delay=5` didn't help.

**Comment by VR-25** [comment]
It turns out this issue is triggered by the kernel.
There's a new acc release.
1. Install it.
2. Run `acc -s sd=1.5; acc -t --%` to see which switches work.
3. Enforce the first with `acc -s s`.
4. Test its reliability. If it doesn't work as desired, try the next. Repeat as needed.

**Comment by jesse-git** [comment]
@VR-25  unfortunately only the same charge switch is reported as before.  the behavior is the same.

 could you elaborate about the kernel or give a link? should I file a bug with them?
