### ISSUE TITLE
acc -s endurance disappeared

### ISSUE THREAD

**Issue by EugenNY** [VR-25/acc#29]
I was using `2019.7.21-r1 (201907211)` on a bunch of phones that were rooted with Magisk and I loved the `acc -s endurance+` feature, it was exactly what I needed since 3-4 years!

But some older phones didn't have Magisk and were rooted with SuperSU. I tried to use the same ACC version there, by manually unzipping the release and running `install-current.sh`. It would try to install somewhat, but I kept getting busybox help screens, as if busybox wasn't compatible. I updated busybox to v1.31.1 but same problem.

I then tried to install the latest dev version `2020.3.14-dev (202003140)` - which installed just fine, no busybox help screens!

However, it appears the latest dev version does not come with the awesome features such as  `acc -s endurance+` - anything I am doing wrong?

I have multiple phones running 24/7 and charging and my goal is to prevent the batteries from expanding and damaging the phones.. which happened quite a few times over the past couple years.

thanks alot

**Comment by VR-25** [comment]
`acc -s endurance+` is really just an _alias_ for `acc 45 44` - meaning, _keep battery level between those numbers._
