### ISSUE TITLE
Unsupport LG V40

### ISSUE THREAD

**Issue by DaysJan** [VR-25/acc#3]
Nice project. I'm not lucky.😝
```shell
judypn:/storage/emulated/0 # acc -L

+ sed -n 's|^capacity=||p' /data/media/0/acc/config.txt
+ '[' 69 -le 30 ']'
+ :
+ true
+ return 0
+ exxit 1 '(!) Unsupported device'
+ typeset 'exitCode=1'
+ set +euxo pipefail
(!) Unsupported device
***EXIT 1***
```

**Comment by VR-25** [comment]
Run `acc --logs --export` and upload the output file.
Thanks:)

**Comment by DaysJan** [comment]
> Run `acc --logs --export` and upload the output file.
> Thanks:)


[acc-logs-judypn.tar.gz](https://github.com/VR-25/acc/files/3304699/acc-logs-judypn.tar.gz)
