### ISSUE TITLE
Samsung Galaxy Note 8 Android 9.0

### ISSUE THREAD

**Issue by sabrican244** [VR-25/acc#37]
Hi i'm using Galaxy Note 8 with custom rom(HadesRom v12) and kernel(Phantom Kernel v2.10)
I tried install latest version using magisk here:
![Screenshot_20200410-195555](https://user-images.githubusercontent.com/8625875/79009317-ddb9a300-7b67-11ea-825f-7e12da972ea9.jpg)
Magisk showed it installed successfully
But app is showing old version installed
![Screenshot_20200410-195530_ACCA](https://user-images.githubusercontent.com/8625875/79009306-db574900-7b67-11ea-94b6-680d2fc8657d.jpg)
If i choose to install acc from inside the app it say "ACC Installation Failed"
![Screenshot_20200410-201257_ACCA](https://user-images.githubusercontent.com/8625875/79009325-e01bfd00-7b67-11ea-90a6-4a0339276b3c.jpg)
Here is the log file:[acc-install.log](https://github.com/VR-25/acc/files/4462651/acc-install.log)

**Comment by VR-25** [comment]
You're using an old AccA version.
It's not compatible with acc beta.
Download v1.0.13 (27) from https://t.me/acc_group/3 .
