### ISSUE TITLE
Charging not re-enabled when a charging switch selected in config

### ISSUE THREAD

**Issue by DanielJutz** [VR-25/acc#41]
Device: Ulefone Armor 3w, Android 9, Magisk
acc version v2020.5.4-rc

Issue: acc -t gives two working charging switches. After reaching pause capacity charging is stopped and a working charging switch is written into the config. plugging in after dropping below resume capacity does not re-enable charging.

janky solution: setting charging_switch to automatic (empty in config) allows charging to be re-enabled. setting `run_cmd_on_pause=acc -s charging_switch=` solves the issue automatically

Everything works great for me now, but I assume that this is not the intended behaviour. I figured out the janky solution because acca resets charging_switch when selecting a profile.

Log: [acc-logs-Armor_3W.tar.gz](https://github.com/VR-25/acc/files/4696038/acc-logs-Armor_3W.tar.gz) (created after first manually setting a charging switch and then clearing the variable which re-enabled charging)

**Comment by VR-25** [comment]
The latest version should have this fixed.
