### ISSUE TITLE
Set charging source priority

### ISSUE THREAD

**Issue by matizk144** [VR-25/acc#45]
Hi!
I would like to achieve to be able to charge phone using fast charge wireless charging wheras USB cable are also connected.

**Use case:**
I have android auto usb only but current from USB port is about 500mA. I have fast wireless change with current about 1600mA. So I want to have usb cable connected for android auto and charge phone wirelessly.

**Notes**
I tried to use Disable USB charging app.. but in the end phone was not charged wirelessly as well. Also I broke power pin (5V) on USB cable.. but head unit in the car not detect connected phone.

**Comment by VR-25** [comment]
Hi,
This is not possible without a dedicated kernel.
