### ISSUE TITLE
Acpi adapter: is not resuming charging 

### ISSUE THREAD

**Issue by matcls** [VR-25/acc#46]
If normal charging I get adapters 0 and 3 online :
Adapter 0: on-line
Adapter 1: off-line
Adapter 2: off-line
Adapter 3: on-line

When acc resumes charging then I have adapters 2 and 3 and it's not charging actually :
Adapter 0: off-line
Adapter 1: off-line
Adapter 2: on-line
Adapter 3: on-line

**Comment by VR-25** [comment]
Hi,
Share the output file of `acc -le`.

**Comment by matcls** [comment]
Hi,
Here is the file
[https://www.dropbox.com/s/2x15cvlrjzunz43/acc-logs-santos103g.tar.bz2?dl=0](url)
sorry for the delay
