### ISSUE TITLE
updater apparently doesn't see the installed version: on purpose?

### ISSUE THREAD

**Issue by elem089** [VR-25/acc#52]
Never had this with any acc version before 202007030:
start acc through termux (tsu > acc)
>>screen shows me that I'm running V2020.7.3 (202007030), and accd is running
from the menu choose "c" >>"check for update"
Next it says "acc 202007030 is available"; I now can download and install, and after that I'm back at the same version.
All the previous versions the updater would see that there is no newer version and wouldn't offer to install the same one again.

I wonder whether this is on purpose?

**Comment by VR-25** [comment]
Fixed!
Thanks
