### ISSUE TITLE
Calling not working

### ISSUE THREAD

**Issue by Hadiuzzaman18** [VR-25/acc#55]
After flashing and rebooting calls are not possible
![Screenshot_2020-07-29-03-46-43-341_com android server telecom](https://user-images.githubusercontent.com/68928666/88729481-d5589880-d155-11ea-812f-bf57e6b3a87c.jpg)

**Comment by pannal** [comment]
Same here with 2020.8.4.

**Comment by VR-25** [comment]
The latest version should have this fixed.
