### ISSUE TITLE
Mi 10 ultra (Xiaomi.eu)

### ISSUE THREAD

**Issue by starraiderx** [VR-25/acc#65]
Hey, ACC doesn't seem to be working for the Mi 10 ultra running miui 12 from xiaomi.eu. I tested the charging switches and it told me to that [dc/input_suspend 0 1] works with -battIdleMode=false. So I went to set it by using the command acc -ss and selecting the forth option. I do not really know what to do with the battidleMode=false information. I also use AccA if that is of any relevance. 

Acc versions affected: 2020.7.26 / .9.14 / .9.24

**Comment by starraiderx** [comment]
How do I send you the log file?

**Comment by VR-25** [comment]
The latest version should have this fixed.

**Comment by starraiderx** [comment]
Still not working. V2020.10.1
