### ISSUE TITLE
Does not works properly on LineageOS kuntao

### ISSUE THREAD

**Issue by dimscor** [VR-25/acc#66]

**Comment by dimscor** [comment]
After the last update of Lineage to 20082020 version accd doesn't works properly. When I start charging, it doesn't pauses as it should according to settings (60%). But I see, that when the charging reaches 60% it stops for 1 sec a few times, but then starts again.

**Comment by VR-25** [comment]
The latest version should have this fixed.
Of yhw issues persists after upgrading, run `acc -t` to see which switches work, then `acc -ss` to manually set one.
For additional details, refer to readme > troubleshooting > charging switch.

**Comment by dimscor** [comment]
The problem is that every switch works, but BattIdleMode=false. And last update didn't fix the issue. Charging doesn't stop permanently, but only for a few seconds.
