### ISSUE TITLE
/dev/accd not be properly linked after installing magisk module with rebooting

### ISSUE THREAD

**Issue by pokon548** [VR-25/acc#67]
When I firstly flash ACC module, it will instantly work properly.
But after rebooting, /dev/adb/acc/acc.sh seems not to be linked to /dev/acc, which make ACC not work.

I'm using v2020.9.24 on OnePlus 7T Pro with Paranoid Android Quartz 4.
Any help would be appreciated. ;)

**Comment by niander** [comment]
Same here. Google Pixel 4XL Android 11

**Comment by VR-25** [comment]
For some time, the delay after boot used to be 5 minutes.
This prevented conflicts with another module (fbind).
The latest version uses a delay of 30 seconds only.
