### ISSUE TITLE
Feature request: sound notification triggered by battery % left

### ISSUE THREAD

**Issue by Polisson** [VR-25/acc#71]
As whole idea is to enhance battery life and one of the most important is to prevent complete discharges, reasonable is to have some feedback when device is idle. 
In more specific it would have user set up value of battery left capacity making play sound (also chosen by user) when battery capacity drop below the value. Ideally would have few such thresholds (and sounds).

**Comment by VR-25** [comment]
The upcoming release is bringing a preliminary implementation of this.
