### ISSUE TITLE
[Magisk Root] Not starting on boot

### ISSUE THREAD

**Issue by fraserdarwent** [VR-25/acc#72]
I'm running Android 11 with Magisk and root. After installing the module the acc service does not start on boot automatically, and some times seems to periodically stop running. Have attempted to re-install through Magisk, or with AccA but same behaviour.

Logs attached.

[acc-taimen-logs.zip](https://github.com/VR-25/acc/files/5340138/acc-taimen-logs.zip)

**Comment by romanegunkov** [comment]
I found that on not fast devices "zygote" process started after checking occurred. As a result "accd" is trying to continue start before system is ready for it.
I fixed it on my device and will make pull request soon.
