### ISSUE TITLE
Fails to trigger Android battery saver when capacity reaches shutdown_capacity + 5

### ISSUE THREAD

**Issue by RadarNyan** [VR-25/acc#75]
The document says that when battery capacity reaches shutdown_capacity + 5, the Android battery saver would be triggered with 5 vibrations, but that didn't happen at all.

Here's my acc config:
```
configVerCode=202010120
capacity=(5 70 50 85 false)
```
(everything below is default value

My intended behavior is:
1. Begin charging capacity drops below 50%
2. Charge with full speed until capacity reaches 70%
3. Stop charging when capacity reaches 85%
4. Shutdown if capacity drops below 5%

All of these behave as I expected, the only thing doesn't work is that nothing happens when capacity drops below 10% ( 5 + 5 ), the only thing do happens is that when the capacity drops below 5% my phone vibrates once then shuts down (so the shutdown_capacity itself works correctly)

I didn't touch the system setting for Battery Saver so it stays at default setting (Turn on automatically disabled), but it still notifies me when battery charge drops below 15%.

Should I wait for my battery charge to drop below 10% again and make a log?

**Comment by VR-25** [comment]
My bad, I forgot to update the documentation.
This feature was removed a while ago.
It had too many dependencies and the setup wasn't straightforward.
I'm exploring alternatives.
