### ISSUE TITLE
Pixel 4a 5G always-on display says phone is charging even when acc has turned charging off

### ISSUE THREAD

**Issue by yaconsult** [VR-25/acc#81]
I just upgraded from a pixel 3a to a pixel 4a 5G and while acc is stopping charging at the 90% charge level that I set, the state-of-charge message on the always-on display is different.

On the pixel 4a 5G, it says "90% - Charging rapidly (26 min until full)" on the always-on display.

On the pixel 3a, it only says "90%" on the always-on display.

Again, acc is functioning properly on both phones because the charge level does not increase above 90%.

So on the pixel 3a, the phone has realized that it is not charging when charging is disabled by acc. But on the 4a 5G, the phone THINKS that it is still charging rapidly even though acc has stopped the charging and the charge level never exceeds 90%.

Does this indicate an issue with the latest android release on the pixel or has the way that acc integrates with android changed somehow in the latest releases? Google DID add the "adaptive charging" feature in the latest update and it is enabled on the 4a 5G. I tried turning both "adaptive battery" and "adaptive charging" off to see if it made a difference in the charging message that appears on the always-on display and it did not.

**Comment by VR-25** [comment]
This is an issue from the Android side of the equation.
[This](https://github.com/VR-25/acc/issues/84#issuecomment-884185159) potential solution to an LG issue applies to this case as well.
Try it and let me know.

**Comment by VR-25** [comment]
This is an issue from the Android side of the equation.
[This](https://github.com/VR-25/acc/issues/84#issuecomment-884185159) potential solution to an LG issue applies to this case as well.
Try it and let me know.
