### ISSUE TITLE
Wireless charging not working if acc is running but yes the wired one

### ISSUE THREAD

**Issue by gerardit** [VR-25/acc#82]
I have a xiaomi mi 10 with xiaomi eu rom and is acc is running the wireless charge dont work. The reverse charge yes and wired charge works too I dont know is its a bug or its something from config. I just installed this module

**Comment by TooYoungTooSimp** [comment]
same issue here, acc can't stop charging wirelessly after battery reached limit

**Comment by VR-25** [comment]
Install the [latest version](https://github.com/VR-25/acc/releases/latest) and share the log archive generated by `acc -le`.
