### ISSUE TITLE
LG V20 Charges to 98%

### ISSUE THREAD

**Issue by Ph0rk0z** [VR-25/acc#84]
Previously setting 80% appears to stop charging at 78% which is fine. Unfortunately trying to get a full charge by setting charge once to 100% leaves the phone at 98% and all charging stops. Both accubattery and ACCA mention charge current is 0. I am able to charge to 100% with bootloader charging.

An odd predicament.

**Comment by VR-25** [comment]
See if `acc -cft=true` helps.
`cft` stands for "capacity_freeze2".

Its original purpose is as follows:
```
# capacity_freeze2 (cft) #
# This prevents Android from getting capacity readings below 2%.
# It's useful on systems that shutdown before the battery is actually empty.
```
You'll be taking advantage of the fact that a side effect of it is keeping the battery level reported by Android in sync with the real value (reported by the kernel).
This  lack of sync seems to be the issue.
Up until now, I though only Pixel devices had this problem.

Closing this now.
Comment if the issue persists after trying the upcoming release and the command above.
