### ISSUE TITLE
Samsung S20+ missing control files

### ISSUE THREAD

**Issue by Boulder08** [VR-25/acc#85]
I tried setting the charging current limit with acc -s c 750, but apparently there's no control files available. I've attached the logs here. Charging limit seems to work fine.

[acc-logs-y2s.tar.bz2.zip](https://github.com/VR-25/acc/files/5828178/acc-logs-y2s.tar.bz2.zip)

**Comment by VR-25** [comment]
It seems you're out of luck with this one, at least for now.
I haven't found any current/voltage control files.
If there are custom kernels for this device, try them out and report back here.
