### ISSUE TITLE
power suspension block plug event

### ISSUE THREAD

**Issue by saiballo** [VR-25/acc#87]
Hi all,

my samsung A41 runs smoothly with acc installed. The problem is about usb connection. I have these capacities:

resume = 70
pause = 95

For example if my battery level is at 80% after recharge it and I connect my phone to the computer, tasker doesn't recognize the "plug" action because battery suspension by acc has block it.

any suggestion? with previous phone, an old android 7, I had not have this problem

**Comment by VR-25** [comment]
It's most likely a device related issue (charging switch).
For details and potential solution, refer to https://github.com/VR-25/acc#charging-switch .
Should you have any difficulty following that, let me know.
