### ISSUE TITLE
Pre-release 201907120: acc log not working

### ISSUE THREAD

**Issue by elem089** [VR-25/acc#9]
just tried acc -l -a cat, as well acc --log --acc cat. Results in
`/sbin/acc[626]: -a not found`
or
`/sbin/acc[626]: -acc not found`
Device is OP6 (same on Xperia z1c). Tested both with on-device terminal emulator and windows command through adb shell
On Xperia Tablet Z not working either, but with different output:
`/sbin/acc[626]: /sbin/.acc/acc-power_supply-pollux_windy.log: can't execute: Permission denied`
Device is rooted, running terminal in 'Superuser' mode

**Comment by VR-25** [comment]
Fixed

If there are no more major issues, the next release (includes this fix and more) will be _stable_.

Thanks

**Comment by elem089** [comment]
ran my first test with this feature: no more error messages, but no log either:
`acc -l -a` opens a vim session in terminal with many empty lines and one last line saying
`/sbin/.acc/acc-OnePlus6.log 1/1 100%`
acc -l -a cat ends up in
`cat: can't open '/sbin/.acc/acc-OnePlus6.log': No such file or directory`
What am I doing wrong?

**Comment by VR-25** [comment]
https://github.com/VR-25/acc/issues/10#issuecomment-513483961
