### ISSUE TITLE
Acc disable in magisk continue starting

### ISSUE THREAD

**Issue by remdu92** [VR-25/acc#90]
Hi guys,

I've installed acc magisk module and acca app to manage it.
I have disabled the acc module in magisk but it's still starting.
I've found with htop that the deamon start with init.d second stage.

After 1hour of research, I can't find where the boot flag is setup ...
Module is disabled so I can not see it in magisk log.

Does someone know why it keep starting ? Related to acca app ?

Thanks in advance.

Ps : last magisk and acc module on a galaxy s20 4g

**Comment by bege10** [comment]
Same issue on Fairphone 3, /e/OS (based on FairphoneOS, LineageOS for microG, Android 10), Magisk 23001, ACC 2021.2.25, AccA 1.0.29.

**Comment by VR-25** [comment]
AccA does not honor Magisk's _module disable_ flag.
Thus, the app is launching `accd` on `boot_completed`.
I'll make acc daemon quit if that flag is set.
Thanks.

**Comment by Rihcus** [comment]
Not sure if this belongs here, does uninstalling acc via magisk instead of from say termux or shell fully remove acc and any modifications. Additionally does acc modify any partitions outside of boot.img of the source rom (ie If I where to reinstall lineage os would modifications from acc still persist).

**Comment by VR-25** [comment]
> Not sure if this belongs here, does uninstalling acc via magisk instead of from say termux or shell fully remove acc and any modifications. Additionally does acc modify any partitions outside of boot.img of the source rom (ie If I where to reinstall lineage os would modifications from acc still persist).

Yes, uninstalling acc via magisk fully removes it too.
Magisk executes acc's uninstall.sh (cleanup script) upon uninstall.
ACC is always systemless - meaning, it never touches any partition besides data.
Modifications made by it to control charging stay in RAM only - a reboot/shutdown resets them all.

**Comment by VR-25** [comment]
The upcoming release has this fixed.
