### ISSUE TITLE
Current control not working on 6T 

### ISSUE THREAD

**Issue by droid-jd** [VR-25/acc#93]
I'm running LOS 17.1 on a oneplus 6T with MCD kernel. For months I've been able to set the current restrictions to 500ma in acca with no problem. Recently, the current control doesn't seem to be working. I've tried setting different values from 250-700 in both acca and acc via terminal emulator (power recommendations from the latest release). Capacity control and idle mode each work fine.

Log output below screenshots.

Thanks for any help!

![Screenshot_20210322-101357_Terminal_Emulator](https://user-images.githubusercontent.com/10563952/112003675-7c2fe180-8af7-11eb-8f09-a7c0a0fb8fe9.png)
![Screenshot_20210322-101406_AccA](https://user-images.githubusercontent.com/10563952/112003677-7cc87800-8af7-11eb-92e2-047c3989d5be.png)
![Screenshot_20210322-101423_AccA](https://user-images.githubusercontent.com/10563952/112003678-7cc87800-8af7-11eb-8a9b-84a46dc5f527.png)

[su -c acc -le output](https://www.dropbox.com/s/qo9zkk8anmh76ax/acc-logs-OnePlus6T.tar.bz2?dl=0)

**Comment by nphantasm** [comment]
I can confirm this issue on Xiaomi A2 Lite running LineageOS 18.1 with stock kernel. Capacity control still works fine.
Using older versions doesn't have any effect.

[acc-logs](https://drive.google.com/file/d/1RI5j0bG9h9c9N-E9F6j21UnYBAPsS0s_/view?usp=sharing)

**Comment by VR-25** [comment]
The latest version should have this fixed.
The changelog states: reapply current settings (e.g., `acc -sc 1800`) after upgrading AND rebooting.
Let me know if the issue persists after that.
