### ISSUE TITLE
Max charge by voltage and not percent.

### ISSUE THREAD

**Issue by Ph0rk0z** [VR-25/acc#98]
I am charging to 80% and because of the battery the voltage at 80% is shifting. It would be nice to use V as a limit and not percent. The gauge on the battery may not be accurate.

**Comment by VR-25** [comment]
For a while I thought about this too.
It wasn't implemented because temperature/current variations and poor battery health cause voltage fluctuations.
But now that you mentioned it, it seems more people would like to have that feature.
I'll work on it.

**Comment by VR-25** [comment]
The next release is bringing this feature.
